apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  # namespace: msp-system
spec:
  # storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: redis-pv