apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis/redis-stack-server:latest
        
        # 1. Override the default entrypoint to bypass the buggy stack wrapper
        command: ["redis-server"]
        
        # 2. Start AOF persistence and ONLY load the ReJSON module
        args:
          - "--appendonly"
          - "yes"
          - "--protected-mode"  
          - "no"
          - "--loadmodule"
          - "/opt/redis-stack/lib/rejson.so"
          - "--loadmodule"
          - "/opt/redis-stack/lib/redisearch.so"
          
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "950Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 6379
          protocol: TCP
        volumeMounts:
          - name: redis-pvc-storage
            mountPath: /data
      volumes:
        - name: redis-pvc-storage
          persistentVolumeClaim:
            claimName: redis-pvc

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: redis
#   # namespace: msp-system
#   labels:
#     app: redis
#   # namespace: envds-cloudy
# spec:
#   selector:
#     matchLabels:
#       app: redis
#   template:
#     metadata:
#       labels:
#         app: redis
#     spec:
#       containers:
#       - name: redis
#         # image: localhost:5000/envds/eclipse-mosquitto:2.0.14
#         # image: envds-registry:36301/eclipse-mosquitto:2.0.14
#         # image: envds-registry:5000/core/eclipse-mosquitto:2.0.14
#         # image: envds-registry:5000/core/redis-stack-server:latest
#         image: redis/redis-stack-server:latest
#         # image: redis/redis-stack-server:latest

#         # command:
#         #   - redis-server
#         #   - "/etc/redis-stack.conf"
#         env:
#         - name: REDIS_ARGS
#           value: "--appendonly yes"
#         resources:
#           requests:
#             memory: "512Mi"
#             cpu: "250m"
#           limits:
#             memory: "950Mi"
#             cpu: "500m"
#         ports:
#         - name: http
#           containerPort: 6379
#           protocol: TCP
#         volumeMounts:
#           - name: redis-pvc-storage
#             mountPath: /data
#           # - name: redis-config
#           #   mountPath: /redis-stack.conf
#             # subPath: redis-stack.conf
#       volumes:
#         - name: redis-pvc-storage
#           persistentVolumeClaim:
#             claimName: redis-pvc