apiVersion: v1
kind: ConfigMap
metadata:
  name: labjack-tx-config
  # namespace: msp
  labels:
    app: labjack-tx
data:
  namespace_prefix: raz1
  envds_env_id: raz1
  interface.conf: |
    uid: ljtx226
    attributes:
      host: 10.55.169.226
      model: T4
    paths:
      i2c:
        path_type: I2C
        sda_channel: 4
        scl_channel: 5
        speed_throttle: 65516
      counter-2:
        path_type: COUNTER
        channel: 2
        counter_mode: "interrupt"
        sample_mode: "unpolled"
        unpolled_interval_handle: 2
        unpolled_sample_frequency_sec: 1
      pwm-6:
        path_type: PWM
        pwm_channel: 6
        clock_channel: 1
        clock_divisor: 1
        clock_desired_frequency: 25000
        counter_mode: "interrupt"
      voltage_in-2:
        path_type: ADC
        channel: 2
        input_voltage_range: 1.0
        input_type: "single"

# tmp
      # voltage_in-1:
      #   path_type: ADC
      #   channel: 1

