---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-ro-secret
  namespace: revpi01-hardware
spec:
  encryptedData:
    .dockerconfigjson: AgC1AI11Gj8Sm+J4UY3bCg5EEGTtpJTSbf5BcQxaJ3OW/1iVfrVzjyd5nj69cqqzZuTVi0dlGQc+cCmfTrKTEBd+Hkp80x/IfJLBfb2JGvxtYOsemeeUqCs2zJHnjwwcVk5j7Tx+kCKQUs9x5oOE9MFOag2JT+hrZz7yHxLvjWosryb3fkApU6Yvv4Gvx2q6AIjEgkxC9sNaDxWf8JmBKmIVpLnx8lNjeXou/vXkkMkDxOCR4Ds8auyjOaj7DuF2KU4pPyxjPdgD4dSPSVRzaMW4mYRX+LHj8gU//N5thkCGYVjCV37pu2D91C6C7Krd+xdZzmrAHWg/BgXZeyRLJi+o+F5sBPCdtt27sNG+15Qhz3DDlqh9V0hjXO7coSShsbTbo1BmLGh+phTKEXlGQfT3RKm3LuduCu7T+93mqT+jrmHTrGa+shDKP1WR4ErAuVxOUGx3p4n/EMvcUOcsVdtkbFtUIk2c3AgtSN+oPv94jXy2sKB7DJ2tn7tu7DOsGKvAeRDbZemOLu0FjaBAsYkgepMOFNYTAsu+XNXzjvTB83bnjAUdJPN4dViJ0XKXM/7whYyOavaeSMiB5/abhd24nykHkTDKdMGIJXop6+bGyCHAPQJ/Spbr42z+SYDpaJxHTLvq+GOo9v0wgFlRpIXCsaz9CV4ZDYUCqBomakwt2hNtaw9uRvsWOWr8o5yDLTg2LviMjdINUY+M6i3QbxRJyenXYbKL6Gp/mJeDklgLP6erG5w994gyZokaMrkfsnaoQaE0zKpwc0ykqpOyXcKlP+SKRpiapmSZHFQ7XTfSwL/pOsREubXoooZppGxXCw5JshU1tgkLOfHpI+J51IFA1ZuC6n8/OKBjCLLOn0LaceWmM+jrc0JAzt6tcii2hehTLEnBFrwQ6cirkjk867WN
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-ro-secret
      namespace: revpi01-hardware
    type: kubernetes.io/dockerconfigjson
