apiVersion: v1
kind: PersistentVolume
metadata:
  name: mqtt-pv-msp01
  # namespace: msp-system
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/envds/mqtt/msp01"