serial_number: "physics-makeup"
daq_id: payload01
interfaces:
  default:
    interface_env_id: payload01
    interface_id: LabJack::Tx::ljtx33 
    path: counter-6
  fan_speed_sp:
    interface_env_id: payload01
    interface_id: LabJack::Tx::ljtx33 
    path: pwm-7

settings:
  fan_speed_sp: 32