apiVersion: v1
kind: ConfigMap
metadata:
  name: sampling-states
  # namespace: msp-system
data:
  daq_id: revpi1

  ENVOPS_DEPLOYMENT_REF: "deploy.pmel.payload_alvan_01_in_acg_alvan"

  port: "8080"
  knative_broker: "http://broker-ingress.knative-eventing.svc.cluster.local/revpi1-system/default"

  mqtt_broker: "mqtt.revpi1-system"
  mqtt_topic_subscriptions: >
    envds/+/sampling-conditions/status/update

  mqtt_port: "1883"

# off
    # envds/+/+/+/data/update,   
    # envds/+/+/+/controller/data/update   
