---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-ro-secret
  namespace: crk8s-system
spec:
  encryptedData:
    .dockerconfigjson: AgA7zPyVpjJMOOQCCQ3/ElOl2diTVh2QUpkOr/2XWLyDbOBOBdtfO14/YJc4AwBFULDVLOHjpvDmFtUwdSslNTZcZ8uRRaL8yMbkAc5NPRDRfs3oxpZwW5O/ZBLTa7d7k/1XytVMrmGLnAhpaGkbZsT8Q8OmtShoTuBgIrgodVDBmBa43boDctKjgg0q5/KH9z3u2uofBmPZHppHn2FIY/Wcrb679c99nn0gjZk+x5MjRS3zGiq2QXbZG+wfzhFSTpDXqWf8gsi3OPpLXs+6zZu2HoXA59RrA+0XObMygtlwdL+iyPX8f77SEf837B9AvmofcujeMYBuRg2l9iz4z8ZuIiN8q6H9Ka1CM31hJ5rrcN0AAAuisdRsk87R7NuVxISwACfJyEDClMZIeIK0YPT1TS+YN9P59USOCiYI68xpFqyi6ty4HtnK2BljfW/Q9U7dKIChA+2LjgFqBjOJhmyhra0HkFPntd6GQdRQdBoRyaHHLUyqzdeqEZsiWGPGL23O35iFlkdztYa8qXkCQUeyI9jOSRUyzti/LxfxPVTZ1R8to16ELn5MSKK3s0HyitTeGubkN35QydcMUnxUul1he9YQJNmLZEDmNVd0mTwQltIZWH9PHFxi4SxQHZVeR/5cEkeeTXmSwO1oG+7UFPxlb9BiB0c5Mffl7x+jgQ9O78V+YWfbN7IloGsstUFr7E8eBP69AwH2NxUn/d9z3saPj3RcDGRJ5jM8zNurXJqQeZOix7/3+Z+lvSvpRw+ePyiqvcsAUxMJvu8qziSEJj14btpzlW0Syinw098uEAy8tyIYHySAWapaleB7r0ospHSeryUWuukYiKhfhlqqkE7HnfPEgdhqL95lQyMVcz8Yt75uFr++clxDA7wW1VlOFu09C4SSqhjX67KmZ8BovN/kzaguAxGWXTEUVkZEWEBqFmQ3fKzZfpwQwIEORSj683T5TQ/fdXjQVxtvOLfhFrpfCQfSmI04/7A+Uw==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-ro-secret
      namespace: crk8s-system
    type: kubernetes.io/dockerconfigjson
