---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-ro-secret
  namespace: crk8s-system
spec:
  encryptedData:
    .dockerconfigjson: AgCw9O5cGuFMODOnuPzmiD1ePDwQwLYiEcw48praLC/fZl8EVgiiQcscKIKV8GCgW6zpe52BhVeEv2/KA5gckQ4Y509qsvGZwclvwpIXng28q1c/rOvi1oeAU5rgKPtrrxTc9Wj3Bo+87CjlmBp95u1/F0rHLUd7zsju7FPG10h+ZON1lWWtg1VPh8yYJco051Erppo8bDXSfC1fSoPito5gju7hct5PojV5lmjHYgcwoXXMf/ZWfijkL956T+uZk1lHKZZNGa7s7qxKd1AK5TSlxDefAqRX84DBEjeFFUaNhJ/51FZaRnbDeIRsNZt0SrmaSJFcPagd+pbx5TYfAXi+WiqvO9CH3AgSGDZxamjFGa67kqEc1m9zsEKjpI9yB+Pu18tULXBQht/VrOUUfdDT/kUCNV/5onk3B7PnkZO4xW89GNQehxyj6fxPZZRfKtxKrL5EIYHkCOprE2w/QNazOyA3pwAd3D52Z5b3xZGMmcTXFTLnoxIrlC4BhCJV+vajJJulufTcXdHQtr37jukWT3pNev3xioLawTPJQdGIY9SKCwKPZIeUoxooGkvqHnk+lfdYjGybdLpsMCAwOBnmBJ3miYfFjpNT6QR7Xr12kRK26OEHk/4GDxHNF2DqmRxsmNsQKjKPMDEvdHZA5S5BnEgP4Mgc+LA33RH3H4Dp7NW3dwP6Ar+QhN2orSojkQnfFpQt951voGFdcD2F7gUL5DYn6gm0gRv//kNW0q4/tdIhid1UCezIT07rwqsyqyQs67gUed4V7jR15ylR6DUE81/wbNA39ip0GROHKe56ilXpWQRYaZ2DWzESTfYyjlQBHeDhk6joL5aKfZLc8PLzxBq1YvdSJ0Uq/6beNqz4aBJmUHDdlnlbDYSl7K1Zg8cYzd18n5Nyunk1FZ7Fsy0W
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-ro-secret
      namespace: crk8s-system
    type: kubernetes.io/dockerconfigjson
