apiVersion: apps/v1
kind: Deployment
metadata:
  name: kn-mqtt-adapter
  labels:
    app: kn-mqtt-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kn-mqtt-adapter
  template:
    metadata:
      labels:
        app: kn-mqtt-adapter
    spec:
      imagePullSecrets:
      - name: ghcr-ro-secret
      containers:
        - name: kn-mqtt-adapter
          image: ghcr.io/noaa-pmel/msp/kn-mqtt-adapter:0.1.7
          imagePullPolicy: "IfNotPresent"
          env:
            - name: KN_MQTT_MQTT_BROKER
              valueFrom:
                configMapKeyRef:
                  name: kn-mqtt-adapter
                  key: mqtt_broker
            - name: KN_MQTT_MQTT_PORT
              valueFrom:
                configMapKeyRef:
                  name: kn-mqtt-adapter
                  key: mqtt_port
            - name: KN_MQTT_MQTT_TOPIC_SUBSCRIPTIONS
              valueFrom:
                configMapKeyRef:
                  name: kn-mqtt-adapter
                  key: mqtt_topic_subscriptions
            - name: KN_MQTT_KNATIVE_BROKER
              valueFrom:
                configMapKeyRef:
                  name: kn-mqtt-adapter
                  key: knative_broker
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 8080