apiVersion: v1
kind: Service
metadata:
  name: kn-mqtt-adapter
  # namespace: msp-system
  labels:
    app: kn-mqtt-adapter
spec:
  selector:
    app: kn-mqtt-adapter
  ports:
  - name: http
    protocol: TCP
    # port: 8000
    port: 80
    # targetPort: 8000
    targetPort: 8080
  type: ClusterIP  
