apiVersion: v1
kind: Service
metadata:
  name: kn-mqtt-adapter
  labels:
    app: kn-mqtt-adapter
spec:
  selector:
    app: kn-mqtt-adapter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080