apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: synaccess-np05b


namespace: payload03-hardware
# Example configuration for the webserver
# at https://github.com/monopole/hello
# commonLabels:
#   app: nginx

# resources:
# # Example configuration for the webserver
# # at https://github.com/monopole/hello
#   nameSuffix: -usc206
#   commonLabels:
#     app: shelly-shellypro3
#     variant: test

resources:
- ../../base
- NP05B-configmap.yaml

nameSuffix: -synaccess25
# patchesStrategicMerge:
#   - deployment.yaml

patches:
  # change configmap names to account for s/n suffix
  - target:
      kind: Deployment
      name: synaccess-np05b
    patch: |-
      - op: replace 
        path: /spec/template/spec/volumes/0/configMap/name
        value: synaccess-np05b-config-synaccess25
      - op: replace 
        path: /spec/template/spec/volumes/1/configMap/name
        value: controller-definition-synaccess25
