apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: erddap-secret
  namespace: mspbase01-system
spec:
  encryptedData:
    insert-password: AgAom4FLDzY1dvNNzRq9FzgJLmLHyauVzBQ09kt6vF8YzL4OatEHpj02unilE8QyZliI3gLgSfGR2HfSZ7FFHC72qpR/WZamgcMb43VyOt4q5hKBa3Oi9wPuY6AkTSiBAV2C1ChKPBYSecrip/gv228E+mtMGoeBr0bRm1PiK7CSN7vPMF4iBW8MPozWRc1W4LueP+no9kR7Nyfw/9dvLczfVkKmPMD83q867PXTGSxOpXCwbSh6wzTvgoC82OEskKWlLYmsib61EV85aAR/dDYAqMeGWW/pABmlCb5hUcdyrm66LZT074wvfQMiUBG1Kgn3emAUVHLni+DRDQY6DFoW2rLjVQFtE3bqpSWg4CXITYWbZYz17oEo14it5tVfiQll3S68nINSF3BvYNnlBGhB0kWZu+PT0/smi3Q8ZKuG0ahClBDn/y8TMRoLDLy4NyyGOiZfXGgKVKuPVdYvIRM7uc17S365BesIQ3af5YYWG2WryY0/Q0vQUU6d4AXB69KNwjXqkRKh1FOfBUE22bzcX4owBMk88jdbTMPiFaHlQerFu7NMcAnjAo0zDJtcPSfhArfvoah81FPXERwpZWug6SQu+147cHDWG+xHiXYMLCaFPM8lD8g8roAYR/lQka5K7I/aUh3SRK9Lhfz9NAJCIp6TUhKY1a1ox9JOiiEko52E9l+RMz/gIVL2UDKThfg1HHs+tZMJIGtnl4V8hmho
  template:
    metadata:
      creationTimestamp: null
      name: erddap-secret
      namespace: mspbase01-system

