apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pmel-dev-system

resources:
  - ../../base

configMapGenerator:
  - name: dataset-storage-config
    envs:
      - configmap.env
      
patches:
  - path: dataset-storage-pvc-patch.yaml