apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaisala-wxt536
  # namespace: msp
  labels:
    app: vaisala-wxt536
spec:
  selector:
    matchLabels:
      app: vaisala-wxt536
  template:
    metadata:
      labels:
        app: vaisala-wxt536
    spec:
      containers:
      - name: vaisala-wxt536
        image: registry-msp:5000/msp/sensor/vaisala-wxt536:0.1.0
        imagePullPolicy: "Always"
        env:
          - name: ENVDS_ENV_ID
            value: mspbase01
          - name: REDIS_OM_URL
            value: redis://redis.default
          - name: LOG_LEVEL
            value: DEBUG
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 9080
          protocol: TCP
        # - name: https
        #   containerPort: 8883
        #   protocol: TCP
        volumeMounts:
            - name: vaisala-wxt536-config
              mountPath: /app/config/sensor.conf
              subPath: sensor.conf
            # - name: mosquitto-certs
            #   mountPath: /certs/ca.crt
            #   subPath: ca.crt
            # - name: mosquitto-certs
            #   mountPath: /certs/server.crt
            #   subPath: server.crt
            # - name: mosquitto-certs
            #   mountPath: /certs/server.key
            #   subPath: server.key
      volumes:
        - name: vaisala-wxt536-config
          configMap:
            name: vaisala-wxt536-config
        # - name: mosquitto-certs
        #   configMap:
        #     name: mosquitto-certs