# apiVersion: eventing.knative.dev/v1
# kind: Trigger
# metadata:
#   name: kn-mqtt-adapter-data-request
#   namespace: msp-system
# spec:
#   broker: msp-system-broker
#   filter:
#     attributes:
#       type: sensor.data.request
#   subscriber:
#     ref:
#       apiVersion: v1
#       kind: Service
#       name: kn-mqtt-adapter
#       namespace: msp-system
#     uri: /mqtt/send
# ---
# apiVersion: eventing.knative.dev/v1
# kind: Trigger
# metadata:
#   name: controller-request
#   # namespace: msp-system
# spec:
#   broker: default
#   filter:
#     attributes:
#       type: envds.controller.control.request
#   subscriber:
#     ref:
#       apiVersion: v1
#       kind: Service
#       name: kn-mqtt-adapter
#       # namespace: msp-system
#     uri: /mqtt/send
# ---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: registry-sync
  # namespace: mspbase01-system
spec:
  broker: default
  filters:
     - any:
        - exact:
            type: envds.registry.sync-broadcast
        - exact:
            type: envds.registry.sync-update
        - exact:
            type: envds.registry.sync-request
     - not:
        exact:
          source: envds.mspbase02.registrar
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: registrar
      # namespace: msp-system
    uri: /registry-sync/
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: registry-sync-to-mqtt
  # namespace: mspbase01-system
spec:
  broker: default
  filters:
     - any:
        - exact:
            type: envds.registry.sync-broadcast
        - exact:
            type: envds.registry.sync-update
        - exact:
            type: envds.registry.sync-request
     - exact:
        # exact:
          source: envds.mspbase02.registrar
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      # apiVersion: v1
      kind: Service
      name: kn-mqtt-adapter
      # namespace: msp-system
    uri: /mqtt/send/


# apiVersion: eventing.knative.dev/v1
# kind: Trigger
# metadata:
#   name: registry-sync
#   # namespace: msp-system
# spec:
#   broker: default
#   filters:
#     - any:
#       - exact:
#           type: envds.registry-sync.bcast
#       - exact:
#           type: envds.registry-sync.update
#       - exact:
#           type: envds.registry-sync.request
#     - not:
#       - exact:
#           source: envds.mspbase01.registrar
#   subscriber:
#     ref:
#       apiVersion: v1
#       kind: Service
#       name: registrar
#       # namespace: msp-system
#     uri: /registry-sync
# ---
# apiVersion: eventing.knative.dev/v1
# kind: Trigger
# metadata:
#   name: registry-sync-update
#   # namespace: msp-system
# spec:
#   broker: default
#   filters:
#     - all:
#         - exact:
#             type: envds.registry-sync.update
#         - not:
#             source: envds.mspbase01.registrar
#   subscriber:
#     ref:
#       apiVersion: v1
#       kind: Service
#       name: registar
#       # namespace: msp-system
#     uri: /registry-sync/
# ---
# apiVersion: eventing.knative.dev/v1
# kind: Trigger
# metadata:
#   name: registry-sync-request
#   # namespace: msp-system
# spec:
#   broker: default
#   filters:
#     - all:
#         - exact:
#             type: envds.registry-sync.request
#         - not:
#             source: envds.mspbase01.registrar
#   subscriber:
#     ref:
#       apiVersion: v1
#       kind: Service
#       name: registar
#       # namespace: msp-system
#     uri: /registry-sync/