apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: setup-brokers-revpi01
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: msp
  source:
    repoURL: https://github.com/NOAA-PMEL/msp-gitops.git
    targetRevision: HEAD
    path: kustomize/apps/setup-brokers/overlays/revpi01
  destination:
    server: https://kubernetes.default.svc
    # namespace: msp-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
