apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-config
  # namespace: msp-system
  labels:
    app: mqtt
  # namespace: envds-base
data:
  mosquitto.conf: |
    sys_interval 1
    autosave_interval 1
    allow_anonymous true
    autosave_on_changes true
    # logs
    log_dest stdout
    log_type all
    log_timestamp true
    log_timestamp_format %Y-%m-%d_%H:%M:%S
    connection_messages true
    # data
    persistence true
    persistence_location /mosquitto/data
    persistence_file mosquitto.db

    # Non-TLS
    listener 1883
    protocol mqtt

    # Bridge
    # connection payload02_mspbase01_bridge
    # remote_clientid payload02_mspbase01_bridge_id
    # address 10.55.169.210:1883
    connection payload02_mspbase02_bridge
    remote_clientid payload02_mspbase02_bridge_id
    address 10.55.169.211:1883
    topic envds/payload02/sensor/+/data/update out 0 "" ""
    topic envds/payload02/sensor/+/settings/update out 0 "" ""
    topic envds/payload02/sensor/+/settings/request in 0 "" ""
    topic envds/payload02/sensor/+/status/update out 0 "" ""
    topic envds/payload02/sensor/+/status/request both 0 "" ""
    topic envds/payload02/sensor/registry/update out 0 "" ""
    topic envds/+/device-instance/registry/update out 0 "" ""
    topic payload/envds/+/registry/sync-bcast out 0 "" ""
    topic payload/envds/+/registry/sync-update out 0 "" ""
    topic payload/envds/+/registry/sync-request out 0 "" ""
    topic main/envds/+/registry/sync-bcast in 0 "" ""
    topic main/envds/+/registry/sync-update in 0 "" ""
    topic main/envds/+/registry/sync-request in 0 "" ""
    topic envds/controller/settings/request both 0 "" ""
    topic envds/device/settings/request both 0 "" ""
    topic envds/sensor/settings/request both 0 "" ""
    topic envds/payload02/controller/+/settings/update out 0 "" ""
    topic envds/+/controller/settings/update out 0 "" ""
    topic envds/+/controller-instance/registry/update out 0 "" ""
    # topic envds/+/controller-definition/registry/update out 0 "" ""
  
    # topic # out 0 "" ""

    # # TLS
    # # https://mosquitto.org/man/mosquitto-tls-7.html
    # listener 8883
    # protocol mqtt
    # cafile /certs/ca.crt
    # certfile /certs/server.crt
    # keyfile /certs/server.key
    # require_certificate false