apiVersion: v1
kind: Service
metadata:
  name: registrar
  # namespace: msp-system
  labels:
    app: registrar
spec:
  selector:
    app: registrar
  ports:
  - name: http
    protocol: TCP
    # port: 8000
    port: 80
    # targetPort: 8000
    targetPort: 8080
  type: ClusterIP  
