apiVersion: apps/v1
kind: Deployment
metadata:
  name: pnnl-sts
  labels:
    app: pnnl-sts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pnnl-sts
  template:
    metadata:
      labels:
        app: pnnl-sts
    spec:
      # THIS IS THE KEY TO UNLOCKING GHCR
      imagePullSecrets:
        - name: ghcr-ro-secret
      containers:
        - name: pnnl-sts
          image: ghcr.io/noaa-pmel/msp/pnnl-sts:0.1.0
          imagePullPolicy: Always 
          
          envFrom:
            - configMapRef:
                name: pnnl-sts-config
                optional: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"  # Set this high enough so the app doesn't hit its own ceiling
              cpu: "500m"
          ports:
            - containerPort: 8080
            
          volumeMounts:
            - name: sts-outbox
              mountPath: /datasets/beacons/sts 
              
      volumes:
        - name: sts-outbox
          emptyDir: {}