---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-ro-secret
  namespace: revpi01-hardware
spec:
  encryptedData:
    .dockerconfigjson: AgBeGN8WZDa5Gs+qke8acjAA0A39aoF7W0hMp0E6KjI1JAwjtpzQCSNYYtK8DWt82v+xpUAJBUAi2TUu+UJhLiajFRk0zZRZ87gfC4rFkg2U8O8/nlPvCQlmwg0rB0Zeiy47s9PDgoo43+5YllAA3zk/MB3LVCXlodv9Sp3F9nrtc2DgxEt3Fwt+XWKgK7kzfPtX0R6zTNqQxnNOaOJr7vkI1VQ917qyE8S+NkP5TmU3KaTybfkNvECZiisZZ2Q6xg9FRDlrrJkYD2iTCH0Vlwgw7G3ZvzS4UaLnUHp4KU0nYwV2KyIEyTi8+f3k1UeS2/SBnfoVoeQU45mPQeDmDUihLuIPRSAHmjOjkkjDdEYoushA1rNs+5Ug8ovFTse9ZcvXUQ2y9HE3DwbfBv+Jk/ZqpvCUC+77UiZ0SQpJvDjVeVg74EkuaqKJVCq1I5AJw/uEHl3iuOjdDXD2iy1iibEyxNDhdf9Nst2JabN53QfIV37a7Di37NPCtXb7DFRjdHhs/pS02VX3KJakAVuKZuxwmrbyfNeG7q+ZrQXE5doiM2z0zmUEeCTr9zraMfp84DoMJXPTxYXO+Ck498njSrbcmXBDdRZc4Hv+rrZKlpfvksjsH1QM8wwzgCOzWx6Bm43gT9WLeDVWRIYayGKlmKmPdDI6k0N8CpWpCbPqdC5ujgK5eRB2Uv8dkaIjX4OO093gF3jfZWlkZ5r9taVFpWgdQEnXOpvRysqE1Ok64htdWHCuxrVMzXkf34YUMWk1Qw0AxP2O/Sy5juWYusndIPl+zrlbTjBFszadpkkRrpNyw4UgazTRgdC+VG2/wIvIeHtbZhBd56U3a8Y9WnyLbiFX7xNMaQ3JP/W3gYfDX4DNLoOtN0ABBF4U1HEMYDE4zh4eSazfsOKtWrPLriEqkuYe
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-ro-secret
      namespace: revpi01-hardware
    type: kubernetes.io/dockerconfigjson
