---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-ro-secret
  namespace: revpi01-system
spec:
  encryptedData:
    .dockerconfigjson: AgACEeiZEHyDVTeFxgqWg4Y0Bq457u1qWNL2jqMgESR8hgjJh9vMX9uriDKYYMtoTgGlyfqhwI4AxhTDblSdoxZv6d4ANbni9/H4CUhm2FORemdxs1jyyMnVxHeB0WVT0DMzDw63FXFaW5jhAGTkEXm5Qj6nfWSzbBDWijnARbLwf5j6rXOcnuIp2O2aOM1c+TL9qrSKtiwr8OV8XsRXuAtRG4jhMjXauscylMqzdU5zQSaQsyc9CNkd42YG8zrNpWfJBIyGWqDEJ+pbirSKbpSVI0dh/cU+eZb4ffwdFpynln8QJSh+AcI5gWfoyWSn5Ot88qN5Osv26EhxHj4ARF6fybqVv/RcHwL5djw54ph7z/JZA4Lq0/MhggoD4x1KnyLoNXqzJeC15QOkO6SJH4SzLwtlodLol/szRtvy4zugF1EDUy8npdDsMbpAvgcGgWSiU3iDCrR8R/OAIs1yo6+BQrmLGhFmMyrQvu3PEPYJf4/PiknP8fSMGc68adyzaBiIkLn+crMkb5a5ZcSGyVRUCSe8Kpo44J4c0Z98kw81Ft6UiA6xLcuLUPqKO4mj0caMIJYgGXDJuAXMlekiB+LhlX6g0zk9DsMCHseATVV5OrxFol/B6AFDCz9chWWZo8F4XJSIlv/lqUbo9DgH/fM1y00G9T9ATHj6emzRliE+eXQ9K6rxleIHqnS0uRuJGH7kWPNq9KviHKIM/SDEL6XB1Jheno4iJoh7S67GzeOieDLak7Rvmv2j9erxfDib8tupK14RL8H1gvQr2uauUjbP6gQiLVOYcz+Suhm4LIJaiUAXyOK8v1Rj22f+THsoSApt9ge0IM+naC64k4VYBkfQCrp65T3ZWrltahGJePCsa9cYhZZOpA1kENWKTZL34JIJDi0nIYT07DohoJZ6QKzX
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-ro-secret
      namespace: revpi01-system
    type: kubernetes.io/dockerconfigjson
