apiVersion: apps/v1
kind: Deployment
metadata:
  name: aerosoldynamics-magic250
  # namespace: msp
  labels:
    app: aerosoldynamics-magic250
spec:
  selector:
    matchLabels:
      app: aerosoldynamics-magic250
  template:
    metadata:
      labels:
        app: aerosoldynamics-magic250
    spec:
      imagePullSecrets:
      - name: ghcr-ro-secret
      containers:
      - name: aerosoldynamics-magic250
        # image: registry-msp:5000/msp/sensor/aerosoldynamics-magic250:0.1.0
        image: ghcr.io/noaa-pmel/msp/aerosoldynamics-magic250:0.1.4
        imagePullPolicy: "Always"
        env:
          - name: ENVDS_CORE_NAMESPACE_PREFIX
            valueFrom:
              configMapKeyRef:
                name: aerosoldynamics-magic250-config
                key: namespace_prefix
          - name: ENVDS_ENV_ID
            valueFrom:
              configMapKeyRef:
                name: aerosoldynamics-magic250-config
                key: envds_env_id
            # value: mspbase01
          - name: REDIS_OM_URL
            value: redis://redis.default
          - name: LOG_LEVEL
            value: DEBUG
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 9080
          protocol: TCP
        volumeMounts:
            - name: aerosoldynamics-magic250-config
              mountPath: /app/config/sensor.conf
              subPath: sensor.conf
            - name: sensor-definition
              mountPath: /app/AerosolDynamics_MAGIC250_sensor_definition.json
              subPath: AerosolDynamics_MAGIC250_sensor_definition.json
      volumes:
        - name: aerosoldynamics-magic250-config
          configMap:
            name: aerosoldynamics-magic250-config
        - name: sensor-definition
          configMap:
            name: sensor-definition
