apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: sampling-states

# set namespace
namespace: mspbase01-system

# Example configuration for the webserver
# at https://github.com/monopole/hello
# commonLabels:
#   app: nginx

# resources:
# # Example configuration for the webserver
# # at https://github.com/monopole/hello
#   nameSuffix: -usc206
#   commonLabels:
#     app: usconverters-uscdr301
#     variant: test

resources:
- ../../base
- sampling-states-configmap.yaml
# - platform_defs_configmap.yaml
# - platform_varmaps_configmap.yaml
# - ghcr-secret-msp-system-sealed.yaml
# uncomment this if using knative for data updates
# - sampling-states-triggers.yaml

configMapGenerator:
  - name: sampling-states-states
    files:
      - sampling_states.json

nameSuffix: "-mspbase01"

patches:
  # change configmap names to account for s/n suffix
  - target:
      # version: serving.knative.dev/v1
      kind: Service
      name: sampling-states
    patch: |-
      # - op: replace 
      #   path: /spec/template/spec/volumes/0/configMap/name
      #   value: sampling-states-mspbase01
      - op: replace 
        path: /spec/template/spec/volumes/0/configMap/name
        value: sampling-states-states-mspbase01

configurations:
  - config.yaml
