apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-ro-secret
  namespace: revpi1-hardware
spec:
  encryptedData:
    .dockerconfigjson: AgC+l3bIW9o0Xx/Ww/9j/mMvDVAlzT1OoplF1MKDq6rz2m6/YZ0yA3ZYep1LvRXQjvcgYStKSvrIumS/VBo25eZiEfFCySPqKn+1w4J+dLmw7bfuLxB4UTBAfru0WL7WvG8QD6knT1IiYGMrzIa9Q0kR4z6ZldYHBLkidOROmU87IzLguJMMqhVnvMkC5szO3Q1BKw4/SHIbQ/K1HlvdFZthZnVS646L+6e3dEmIN31qxhp6t1Mo+nykAXlHq287F4HKQIfMs/XRc/Utd8YRarqA5ZQj7byGNcNIe4j5CTfwkQcyf3lP2z3pzqA7yZGjC+x/6KAICwq4pn3G5+GcC2NRzjxbCracFSfcbW23bkw9Ue8lL6W2QsNlR59ZnRbPtiYdVugqJttvOsSN/w4N9InAkkdeBFBczpj4V+gB+UtH+STGCDIuaDFTEB9Y0x/Qab/6sC62bcqjZxSNUIpAXZV8Jz35oRBMW43Kyg73wxrGwTBTHgkn00BKhol8W6SKeRDiqFGfOjifxU390ihvM72Q+3zRDGcobMP4SaY71n3oF1YKWD8Q40ciZGpO7Wn3ws2MRrFj0qFZTlr3korBntOJZRRlFioaSMcfcDTMiYbYGWBnvdg1QoNEdR79oTHW9s1JLZCY6IJQ4o07dnXrGQsbT1RGZZaJ5FYYzHzWvTvIGH7dZysWH6ZFRadCn5n4Oa5yjhRvNLHcEYhqjFG6sdcxGW2mGQMPvqDC4pkFya0c1O6CW3cm8cMk/JAZV97xh8SZfYyvC5KnzskOsf6xjEZQFhM0WFPDPlTc9olBWKoR/JzHIE6P9ilzPEM9BOG4cT5EMdUywfLOEa7RDYWPlv/VhDhD0L5QDiB0Y02c1jrhrHIT9xPIfdEa7T/36WaTzncKnYyJshfn6evY9V1cEQPZ
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-ro-secret
      namespace: revpi1-hardware
    type: kubernetes.io/dockerconfigjson

