apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-ro-secret
  namespace: revpi1-system
spec:
  encryptedData:
    .dockerconfigjson: AgBSMKOjvv4XupSCzxFPYro4vykF/hsNUSMH/XyzHW6PEqRBMtxdeCcTt6s90jrY0NwYnT2DcKQ/uER3HNd2mNlPgDc0xC1r84Mt7okt1lR4dailioiTtpbtFm8ic1aeV34NixxruF7by+rYXW49QFZ8V/aD5J8k/yMgW2QtP/jyeZ9KRKOUEqbAh+QMYkWGE+dbxh7rIwn6DFPv8HGBjXI5wfFzAf27NzsLHNV71ju3Kn8gLSAnunhpSRAHxuWjy7Yp1KENLnKiEtlE1xrsfLeNBZ1uJ2PSzXlr/da0rtaLE0UTkDMqi64nA3oR2r8vDpH2ls/qoHRkf6ushdCO8RRspu4knx1rskOPvciXY/PpOhvk2V4ADtrv6tmUFrhjXO8qvuwEkNP3Cu3/LamVVIfIoraE/fK7vK3isCbRMaqdch8DoQSiYRE0/TEkYkGov+A6JdZqvMABX9SK9FYDvyzEQ60XAps0kEZtumW52U32yOROIiJGapSl9XKB9g5T4V8UWNEfR5NpAapwIMKV5n5MyDe3Nf21wForMFudOP2oLztSlXoGlu+38aDKJ9ohGPhC4pY2sajRg6Lpz8qOClpklikZ7cuLV5FCdDuprDz9beYx97IGKMYB+w7yTuPHC5ANqXcn33Wx7sFcTnpXO2JLqbnKBDKETeQZv3My6EL3HBlB7zzE/wET4Lcu++oe8qdDM95+mdDRJmOW3G0J7GMq5uRA8hJpjDqqZGL7g4OPFzBACC1PFmXA4mHWEf3p/bzgnaiN77tSrBoPyA9oUz8eyatp2ctcbNV04zLS77q6OC8qDIw6OyMIOq6AztS6s28EjXeTXoho4RZdwD4Cl6RD3UhV6f2vDACvX2VHB97rVwasehg/2NIg7KtZTUpRMYlBtdwShtfTq2hXteVHtkHM
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-ro-secret
      namespace: revpi1-system
    type: kubernetes.io/dockerconfigjson

