apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-ro-secret
  namespace: revpi2-hardware
spec:
  encryptedData:
    .dockerconfigjson: AgA9MKVpozv3q5i4MSUffQI1keyIzm5Fj6Ewmapu6E9BpzCMjrowNZCkQiMK7UezT0r3v37Rv4s1eiWHrrPx49MheyFEFnSQbqSA9EsIm8WOvHAFaN1wepacGuu0KUAsWEs9a2kOCwVNmfbvirEfEDZrnRgpno0Q1w+fJEn7poGhPLq3mQop8BROVrWAmZs8sz2HPYZ82lTkPUVog25xSreL13j+8FWk35OkzGu1hjBclHNN9+F4lg8w2U7CyyEjC1x4yCUMVFNo7ymLzQiF64JqIFfu+xcr/LWJARKXlty5Uf/FAeJdYN0Em0GAnBrViSdbYVDuAUuPXTK4S7fwsUCQ3Io75d/3nyN5O07W53IFPkQdaTvdQfJoJXLFaa3Zq4/mVj6yYOHCLOZt3d5DmMKgwMmaYr26ZN8hZBlsoA07VFsvebQfAmTF6h8dBWbw7jMiKl+qVk0z+c3NSOCOBPFqdXhwvCsStS/+aMNtW79Ju7kuCYh3kR+LnINBY/PsoBHiX2+jOnmjkUGZA5jgofNaJAPolliBLaxUL0KFskHiZN4zCIWfR7OettglcEYgJhaJyH3RNWzYt7J8UPpg5WQATb/oSmmSQ+HKTrCvxSuSjutPH7hqLpRx60LZSrqMsENSTv9AhKdQEO8tNCOhA6MgFvWLgYdXef2LpMkiKMk6DMCb/2we2dL/rzc+7UqcrdKZ7lsq+aDA5GsLU3jnemTF5IvSWN4ATCYFVgKudSYiLHM9+2hJHlvFvNQehz4nlZeKieWhwxMcdF+SfLmL4nsAMcJHRkd02VetEWj4YllL2pzYIk1ha0ZUls1h8y8hbep4BM8HcAHfxjAhs4zqGVaoQBiMDAh5QGu3ZGwBxUPzKSEt/aQ7GcNDguE6105kWrNpCw6goNMZPMWsHm9O3Y2A
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-ro-secret
      namespace: revpi2-hardware
    type: kubernetes.io/dockerconfigjson

