apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastore
  labels:
    app: datastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datastore
  template:
    metadata:
      labels:
        app: datastore
    spec:
      imagePullSecrets:
      - name: ghcr-ro-secret
      containers:
        - name: datastore
          image: ghcr.io/noaa-pmel/msp/datastore:2.0.0
          imagePullPolicy: "Always"
          env:
            - name: DATASTORE_PORT
              valueFrom:
                configMapKeyRef:
                  name: datastore
                  key: port
            - name: DATASTORE_DAQ_ID
              valueFrom:
                configMapKeyRef:
                  name: datastore
                  key: daq_id
            - name: DATASTORE_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: datastore
                  key: log_level
                  optional: true
            - name: DATASTORE_DB_CLIENT_TYPE
              valueFrom:
                configMapKeyRef:
                  name: datastore
                  key: db_client_type
            - name: DATASTORE_DB_CLIENT_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: datastore
                  key: db_client_hostname
            - name: DATASTORE_DB_DATA_TTL
              valueFrom:
                configMapKeyRef:
                  name: datastore
                  key: db_data_ttl
            - name: DATASTORE_DB_REG_DEVICE_DEFINITION_TTL
              valueFrom:
                configMapKeyRef:
                  name: datastore
                  key: db_reg_device_definition_ttl
            - name: DATASTORE_DB_REG_DEVICE_INSTANCE_TTL
              valueFrom:
                configMapKeyRef:
                  name: datastore
                  key: db_reg_device_instance_ttl
            - name: DATASTORE_DB_CLIENT_PORT
              valueFrom:
                configMapKeyRef:
                  name: datastore
                  key: db_client_port
            - name: DATASTORE_MQTT_BROKER
              valueFrom:
                configMapKeyRef:
                  name: datastore
                  key: mqtt_broker
            - name: DATASTORE_MQTT_PORT
              valueFrom:
                configMapKeyRef:
                  name: datastore
                  key: mqtt_port
            - name: DATASTORE_MQTT_TOPIC_SUBSCRIPTIONS
              valueFrom:
                configMapKeyRef:
                  name: datastore
                  key: mqtt_topic_subscriptions
            - name: DATASTORE_KNATIVE_BROKER
              valueFrom:
                configMapKeyRef:
                  name: datastore
                  key: knative_broker
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
          # Standard Kubernetes Probes
          startupProbe:
            httpGet:
              path: /
              port: 8080
            failureThreshold: 30
            periodSeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 15
            timeoutSeconds: 5