# base/datastore-triggers.yaml

# --------------------------
# DEVICES & CONTROLLERS
# --------------------------
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: datastore-device-definition-registry-update
spec:
  broker: default
  filter:
    attributes:
      type: envds.device-definition.registry.update
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: datastore
    uri: /device-definition/registry/update/
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: datastore-device-registry-update
spec:
  broker: default
  filter:
    attributes:
      type: envds.device.registry.update
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: datastore
    uri: /device/registry/update/
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: datastore-controller-definition-registry-update
spec:
  broker: default
  filter:
    attributes:
      type: envds.controller-definition.registry.update
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: datastore
    uri: /controller-definition/registry/update/
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: datastore-controller-registry-update
spec:
  broker: default
  filter:
    attributes:
      type: envds.controller.registry.update
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: datastore
    uri: /controller/registry/update/
---
# --------------------------
# SAMPLING SYSTEM (VARMAPS)
# --------------------------
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: datastore-project-definition-registry-update
spec:
  broker: default
  filter:
    attributes:
      type: envds.project-definition.registry.update
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: datastore
    uri: /project-definition/registry/update/
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: datastore-contact-definition-registry-update
spec:
  broker: default
  filter:
    attributes:
      type: envds.contact-definition.registry.update
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: datastore
    uri: /contact-definition/registry/update/
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: datastore-platform-definition-registry-update
spec:
  broker: default
  filter:
    attributes:
      type: envds.platform-definition.registry.update
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: datastore
    uri: /platform-definition/registry/update/
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: datastore-deployment-definition-registry-update
spec:
  broker: default
  filter:
    attributes:
      type: envds.platform-definition.registry.update
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: datastore
    uri: /deployment-definition/registry/update/
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: datastore-variablemap-definition-registry-update
spec:
  broker: default
  filter:
    attributes:
      type: envds.variablemap-definition.registry.update
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: datastore
    uri: /variablemap-definition/registry/update/
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: datastore-variableset-definition-registry-update
spec:
  broker: default
  filter:
    attributes:
      type: envds.variableset-definition.registry.update
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: datastore
    uri: /variableset-definition/registry/update/
---
# --------------------------
# SAMPLING MANAGERS
# --------------------------
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: datastore-samplingcondition-definition-registry-update
spec:
  broker: default
  filter:
    attributes:
      type: envds.samplingcondition-definition.registry.update
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: datastore
    uri: /samplingcondition-definition/registry/update/
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: datastore-samplingstate-definition-registry-update
spec:
  broker: default
  filter:
    attributes:
      type: envds.samplingstate-definition.registry.update
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: datastore
    uri: /samplingstate-definition/registry/update/
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: datastore-samplingmode-definition-registry-update
spec:
  broker: default
  filter:
    attributes:
      type: envds.samplingmode-definition.registry.update
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: datastore
    uri: /samplingmode-definition/registry/update/
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: datastore-action-definition-registry-update
spec:
  broker: default
  filter:
    attributes:
      type: envds.action-definition.registry.update
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: datastore
    uri: /action-definition/registry/update/
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: datastore-systemmode-definition-registry-update
spec:
  broker: default
  filter:
    attributes:
      type: envds.systemmode-definition.registry.update
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: datastore
    uri: /systemmode-definition/registry/update/