apiVersion: v1
kind: ConfigMap
metadata:
  name: sensirion-sdp810-config
  # namespace: msp
  labels:
    app: sensirion-sdp810
    # app-group: envds-sensor-payload03
    app-group: envds-sensor-crk8s
data:
  namespace_prefix: revpi2 
  envds_env_id: revpi2
  # namespace_prefix: mspbase01 
  # envds_env_id: mspbase01
  sensor.conf: |
    serial_number: "inletflow"
    daq_id: revpi2
    interfaces:
      # default: serial
      default:
        interface_env_id: revpi2-hardware # if omitted, defaults to envds_id of sensor
        interface_id: LabJack::Tx::ljtx226
        path: i2c
    i2c_address: "28"

    
    