apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: aerosoldynamics-spidermagic810

namespace: payload03-hardware


# namespace: payload03-hardware
# Example configuration for the webserver
# at https://github.com/monopole/hello
# commonLabels:
#   app: nginx

# resources:
# # Example configuration for the webserver
# # at https://github.com/monopole/hello
#   nameSuffix: -usc206
#   commonLabels:
#     app: usconverters-uscdr301
#     variant: test

resources:
- ../../base
- spidermagic810-configmap.yaml

nameSuffix: "-011"

# patchesStrategicMerge:
#   - deployment.yaml

patches:
#   # change configmap names to account for s/n suffix
  - target:
      kind: Deployment
      name: aerosoldynamics-spidermagic810
    patch: |-
      - op: replace 
        path: /spec/template/spec/volumes/0/configMap/name
        value: aerosoldynamics-spidermagic810-config-011
      - op: replace 
        path: /spec/template/spec/volumes/1/configMap/name
        value: sensor-definition-011
