apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: setup-namespace

# Example configuration for the webserver
# at https://github.com/monopole/hello
# commonLabels:
#   app: nginx

# resources:
# Example configuration for the webserver
# at https://github.com/monopole/hello
# namePrefix: dev-
# commonLabels:
#   app: nginx
#   variant: lopez

resources:
- ../../base
- namespace.yaml
# - ghcr-secret-mspbase02-system-sealed.yaml
# - ghcr-secret-msp-events-sealed.yaml

# patchesStrategicMerge:
#   - deployment.yaml