apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dataset-generator-pmel-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: msp
  source:
    repoURL: https://github.com/NOAA-PMEL/msp-gitops.git
    targetRevision: HEAD
    path: kustomize/apps/datasets/dataset-generation/dataset-generator/overlays/pmel-dev
    kustomize:
      # ---> THIS FORCES THE FLAG ON NEWER ARGOCD VERSIONS <---
      buildOptions: "--load-restrictor LoadRestrictionsNone"
    # kustomize:
    #   patches:
    #     - patch: |-
    #         - op: replace
    #           path: /spec/subscriber/ref/namespace
    #           value: mspbase02
    #       target:
    #         kind: Trigger
  destination:
    server: https://kubernetes.default.svc
    # namespace: payload01
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
