apiVersion: v1
kind: ConfigMap
metadata:
  name: system-modes
  # namespace: msp-system
data:
  daq_id: mspbase01
  port: "8080"
  knative_broker: "http://broker-ingress.knative-eventing.svc.cluster.local/mspbase01-system/default"

  system_init_control: "auto"
  system_init_mode: "startup"
  is_primary_controller: "false"

  mqtt_broker: "mqtt.mspbase01-system"
  mqtt_topic_subscriptions: >
    envds/+/+/+/data/#,
    envds/+/system-modes/#,
    envds/+/sampling-modes/#

  mqtt_port: "1883"
