apiVersion: v1
data:
  .dockerconfigjson: ICAgIHsKICAgICAgImF1dGhzIjogewogICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgImF1dGgiOiAiZ2hwXzlUcWR1V3pxUE5BdkFPcndUUXl3RlpqWVJuTlNFUzNrTm15OSIKICAgICAgICB9CiAgICAgIH0KICAgIH0=
kind: Secret
metadata:
  creationTimestamp: "2025-05-20T21:19:32Z"
  name: ghcr-ro-secret
  namespace: mspbase01-system
  resourceVersion: "4457671"
  uid: 44cc6ca9-ba24-4a45-b0ba-50b90afadccf
type: kubernetes.io/dockerconfigjson
