apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-ro-secret
  namespace: mspbase01-hardware
spec:
  encryptedData:
    .dockerconfigjson: AgCKT1Z+KXW2seWeagd2IMK1aav/CdF4hBONvWqURukCXInyHMROGc1enaEcjpeyJJIpYtnxWmG2W64pvuDCwJHg1NuaUiFtQm7Vut8YuhDHkE/p3JgFKAiTXPXgGsw2XiuIIkZZjGqgNmMe1v0KGQBS0bIhL2s0SDGXFIcAacsYjnSWN3ZVQy8PfANPpl96D1k4SE9+egOTz6cJkoerbRHP1YLEEtFZQG7TwKeodPNkT3HdmwsRVnHT5Q0IHzHzbAWjZu7A3DNu4baJwvnhusRTDvkvZoFKQgh4yoKSADW/Z5KpGYwiycX5bOQgYfJ1Rx1xE8S4+cG1MDZgH4kRCeDAZNjyNi0qK9H0M5pJMJYjTsrQ6uGlU1nGT84+fj1OMIwzbQ8iZ7xZ6npbJWo9xD5R1ygiQSC0Rs5GMjKVrcd+07zO2r8OfPKn6vPRhMUE5kngWE+iVe+fgbzO97Bi/LGfoVdrsztnO7bHiPtn3JHTQ2BSjyb4dkiNeyGIWZdn2CkaDgWbeGfZhismBu7iADMxgv0GQIWg1XfkiPSJIkIPQxJ8nCpPwS5re+Xl0Ga+KBkXgu5VL2BX+1iGfFpv0TWsCrEHpCeM2wS0D2gZnu+/+c7hXulFH7f7ujjlReUrDDXH/c+2IFOTv51ppx4bAK3BBMcSGhhF7TVecQ7UzvyJiMCtNX0tRibBApqpm2C8pwdoUw2ygs7DEdLpjnDyqxIV8ZzcTAjbbfyKlbXCJrnzHu45stPXiuqsl4gOdWWecfoSK53zKlxErbbTPB+QeodNWam96uoLTLtYl9AYLprTawprs0MNAMmE9zdCBT0rzQELFyvXEF/nk09TR4QpFBtsd27HxcGcTxEsNFI7Bi3dGw==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-ro-secret
      namespace: mspbase01-hardware
    type: kubernetes.io/dockerconfigjson

