apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: MTChannelBasedBroker
  name: default
  namespace: payload03-system
  delivery:
    retry: 5
    backoffPolicy: exponential # or linear
    backoffDelay: "PT0.5S"     # or ISO8601 duration
# ---
