apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: qc-operations-stored-trigger
spec:
  broker: default
  filter:
    attributes:
      type: envds.dataset.stored
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: qc-operations