apiVersion: apps/v1
kind: Deployment
metadata:
  name: erddap
spec:
  template:
    spec:
      containers:
      - name: erddap
        env:
        - name: ERDDAP_MIN_MEMORY
          value: "2G"  # Reduced from 4G
        - name: ERDDAP_MAX_MEMORY
          value: "4G"  # Reduced from 8G
        resources:
          requests:
            cpu: 250m     # Reduced from 1000m
            memory: 2.5Gi # Reduced from 5Gi
          limits:
            cpu: 2000m    
            memory: 5Gi   
      - name: erddap-sidecar
        resources:
          requests:
            cpu: 100m     # Reduced from 500m
            memory: 128Mi # Reduced from 256Mi
          limits:
            cpu: 500m
            memory: 512Mi