apiVersion: v1
kind: ConfigMap
metadata:
  name: kippzonen-splite2-config
  # namespace: msp
  labels:
    app: kippzonen-splite2
    app-group: envds-sensor-raz1
data:
  namespace_prefix: raz1
  envds_env_id: raz1
  sensor.conf: |
    serial_number: "742"
    daq_id: raz1
    interfaces:
      default:
        interface_env_id: raz1
        interface_id: LabJack::Tx::ljtx226
        path: voltage_in-5_4


# tmp        
#       ref_volt:
#         interface_env_id: raz1
#         interface_id: LabJack::Tx::ljtx207
#         path: voltage_in-1


