apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: brechtel-tap2901

namespace: payload02-hardware

resources:
- ../../base
- tap2901-configmap.yaml
# ADD THE NEW PV HERE
- tap2901-pv.yaml

nameSuffix: "-052"

patches:
  # (Your existing deployment patch for the configmaps remains)
  - target:
      kind: Deployment
      name: brechtel-tap2901
    patch: |-
      - op: replace 
        path: /spec/template/spec/volumes/0/configMap/name
        value: brechtel-tap2901-config-052
      - op: replace
        path: /spec/template/spec/volumes/1/configMap/name
        value: sensor-definition-052
        
  # NEW PATCH: Bind the generic base PVC to the specific 052 PV
  - target:
      kind: PersistentVolumeClaim
      name: tap2901-state-pvc
    patch: |-
      - op: add
        path: /spec/storageClassName
        value: local-host-mapped
      - op: add
        path: /spec/volumeName
        value: tap2901-state-pv-052