apiVersion: v1
kind: ConfigMap
metadata:
  name: brechtel-tap2901-config
  # namespace: msp
  labels:
    app: brechtel-tap2901
    app-group: envds-sensor-payload02
data:
  namespace_prefix: payload02
  envds_env_id: payload02
  sensor.conf: |
    serial_number: "052"
    daq_id: payload02
    interfaces:
      # default: serial
      default:
        interface_env_id: payload02-hardware # if omitted, defaults to envds_id of sensor
        interface_id: USconverters::USCDR301::usc16
        path: port-1
      #   connection-properties:
      #     baudrate: 115200
      #     bytesize: 8
      #     parity: N
      #     stopbit: 1
      #   # read-properties:
      #     read_method: "readline" # default
      #     # terminator: "\r"
      #     # binary: true
      #     # num-bytes: 1
      #     # decode-errors: strict
      # # power: # example of second interface (e.g., CDP enable signal)
      # #   interface_id: system::mock::localhost
      # #   path: port-01
      
    # settings: # used to override defaults
    #   pump_power: 1
    #   q_target: 300