apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mspbase01-system

# Give all resources in this kustomization standard labels
commonLabels:
  app: envops
  platform: mspbase01

resources:
  - ../base                   # Points to your base deployment, service, and ingress files
  - envops-configmap.yaml     # Applies the mspbase01 environment variables
  - envops-triggers.yaml      # Applies the Knative routing rules (from the previous step)