apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telemetry-proxy-secret
  namespace: pmel-dev-system
spec:
  encryptedData:
    encryption_key: AgB5mOS8T/R0LLvNG2oWymtXIZSuvn+rcXNv0dPTCFi1Geq697oSGql5O6HD6P622gqyjmB551F6ZAuRe+lFOvulbZEBHFnTz5WB1GnHvpVNgUBxxcxu/NqFRh4h/GsiRagFl/BQMydIR5ebYSpE2TeIt1qxRNSfdhYjL8jYoLzZvD05ocxgAsHof6L6J+0qEksELBMgwQGi5HxScBz/hUwJebOMsGgAi7V6Pbtpv94XTedncos+sS3w25meMO2H5mYaI0udhAt//6zLq4eiHj1lC7l86WEkqR50AxiudyOWgglnZxuiz7VGmO1Z8a7xEa7kI1UzS48kx3X/1qdenBRVCHG5Ixd7siANwv7w2aj7HXyPKRcujrDEwI8b4OKo4a6jNtGlm9fgWbmKXNMRf8tirdeRmxBPu4ThKsU6QO9dLjk6n1iRHN+G0hcbsEc8Vj6UJaxYtq0Ecy8hchXRmR1F+spkOFGTkApRiT+1KUN2C14mOF3m0POEC2UG9x2HyxRbZIS0avPPxZmF8GMMicMdItgoNBL0yhRAy18nKMOjhRRWGAbJ1ZJgTkePtyB0Gcn3CqSmjFuFhW1bhK1x5bO4btbx7KszvEYeGpkXof9AzJWX4qNpX+lOjzH2giFCNeZt/GnJC8JwwL0NqIx6pBKYvM4CoUHYkeRvKV10aZWKmx1ktH3yX56fCuMS1AkgpCMmYmxUEPP6L9WWUSMci6Gf2POiNNskWQo8TSczwdencg==
  template:
    metadata:
      creationTimestamp: null
      name: telemetry-proxy-secret
      namespace: pmel-dev-system

