apiVersion: v1
kind: ConfigMap
metadata:
  name: shelly-shellypro4pm-config
  # namespace: msp
  labels:
    app: shelly-shellypro4pm
data:
  namespace_prefix: mspbase02
  envds_env_id: mspbase02
  controller.conf: |
    uid: shel223
    host: 10.55.169.223
    client_host: mqtt.mspbase02-system
    client_port: 1883
    controller_id_prefix: shellypro4pm

    # override definition values
    attributes:
      serial_number: shel223
    # variables:
    #   channel_2_power:
    #     default_value: "0"
