apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dataset-storage-pvc
  namespace: envds
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi # Adjust based on your expected backlog of .nc files