apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-ro-secret
  namespace: payload01-system
spec:
  encryptedData:
    .dockerconfigjson: AgAEuaT1rnPbZUujmw2Y6mESZ2Qt9Al0KZkLESywiKRKjbFgk7y4KZSW1QwKOXrKa8ngMNE/Whh/2Eu814zsgNrIwTuArG9spuMIScq29rv93TOMtv/aspDByjKiP8RDODqu3XiHmdWSSEJ0oZjqtRuVNytRSE4mnIhfY+ZzmDN1A2qkp1ql3oPHpWcEgRVHXfNdTrW0V4Ewc4RwRpeuH2ZZWYkbatwmtkOIyIH4CSeIpG+AiPNcYUeU/0TWJbHtgKRbfDHV3le2YUCs6NUwaoimNWSgYibxn7NerNtTMxMT16WMx//rsxXP0lidXtR1tU4CzqOwo6lgGMqJbLYV0CSw6+WgW3WAXIH1Hu3TeuHPfozRb6unfiSdzOA+vgnZlJYkQJwp2GyJ1K3g/6I8j+4d3AFFkjDt2Wd8k3fXEU0IVgjzUV2oq+wY9kzSWDKaB9PB68p9+W3dTeiKmhCrcJfHaPGY6JOCD17ZZncrCX0dPOQoOf55b6GQCYWBhv2HIME3MScoLSGV58Cxtms4RPv8hncEcTfnZYLo32hZK8ETJaKrvvfBvyeewcP6ychZzkwNh5jUEer6aMN59j6GdVC66FI7KJ+gznXfIj9k/gRy4qgUNPkQOBGw5m7TZR8oMw24L9BMDoVSmRW4ROsAuyCaeRn1fEtelqi7rUuF4O4XZS1VLY5lCwknI9kecOxhqZKFBnwH0A7aA2HHm22FTdUO9/+6onUOpF960jWOdkmIUmK41+MfjtjkHHo9WX+NmCibgaaIJjK5iZNwyM1H4ZQyl2t/kU2ipGiv8CFO1mYuu3/zQx6LlRudY4I2XZsHCT0cRwhiXEz/rZzJiNpOCOmTE/9TZkJYhqtREnb3WW9qj3C/spyHIJOZT25NB+nRy2XR+pSoQULcvz+h8qQa/6cX
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-ro-secret
      namespace: payload01-system
    type: kubernetes.io/dockerconfigjson

