apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: trigger-aerosol-physics-daily-a1
spec:
  schedule: "40 1 * * *"
  contentType: "application/json"
  data: '{ "dataset_id": "san_hnl.aerosol_physics.a1", "action": "generate", "time_window": "auto" }'
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: dataset-generator
    uri: /dataset/generate/request/
---
apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: trigger-aerosol-optics-daily-a1
spec:
  schedule: "41"
  contentType: "application/json"
  data: '{ "dataset_id": "san_hnl.aerosol_optics.a1", "action": "generate", "time_window": "auto" }'
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: dataset-generator
    uri: /dataset/generate/request/
---
apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: trigger-aerosol-sizing-daily-a1
spec:
  schedule: "42 1 * * *"
  contentType: "application/json"
  data: '{ "dataset_id": "san_hnl.aerosol_sizing.a1", "action": "generate", "time_window": "auto" }'
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: dataset-generator
    uri: /dataset/generate/request/