# datasets/dataset-generation/dataset-generator/overlays/pmel-dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Target namespace for this specific overlay
namespace: pmel-dev-system

resources:
  - ../../base
  - dataset-generator-triggers-daily.yaml
  # - dataset-generator-triggers-hourly.yaml
  # - dataset-generator-triggers-5min.yaml
  - ../../../../definitions/base

configMapGenerator:
  - name: dataset-generator-config
    envs:
      - dataset-generator-configmap.env