# datasets/dataset-generation/dataset-generator/overlays/pmel-dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Target namespace for this specific overlay
namespace: pmel-dev-system

resources:
  - ../../base
  - dataset-generator-configmap.yaml
  - dataset-generator-triggers.yaml

configMapGenerator:
  - name: dataset-definitions
    files:
      # Step up 4 levels to the repo root, then down into definitions/
      - ../../../../definitions/san_hnl.metnav.a1.json
      # You can continue adding future definitions here!
      # - ../../../../definitions/payload_03.aerosol.a1.json