apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tap2901-state-pvc
  labels:
    app: brechtel-tap2901
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-host-mapped
  resources:
    requests:
      storage: 50Mi