apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kn-mqtt-adapter

namespace: mspbase02-system
# Example configuration for the webserver
# at https://github.com/monopole/hello
# commonLabels:
#   app: nginx

# resources:
# # Example configuration for the webserver
# # at https://github.com/monopole/hello
#   nameSuffix: -usc206
#   commonLabels:
#     app: usconverters-uscdr301
#     variant: test

resources:
- ../../base
- kn-mqtt-configmap.yaml
# - adapter-triggers.yaml
# - datastore-sealedsecrets.yaml

# spec:
#   template:
#     metadata:
#       # labels:
#       #   app: kn-mqtt-adapter
#       annotations:
#         autoscaling.knative.dev/min-scale: "1"

patches:
  # change configmap names to account for s/n suffix
  - target:
      # version: serving.knative.dev/v1
      kind: Service
      name: kn-mqtt-adapter
    patch: |-
      - op: replace 
        path: /spec/template/metadata/annotations/autoscaling.knative.dev~1min-scale
        value: "1"
