apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: sampling-conditions
namespace: revpi1-system

resources:
- ../../base
- sampling-conditions-configmap.yaml

configMapGenerator:
  - name: sampling-conditions-conditions
    files:
      # Reusing the shared modular templates!
      - ../../shared_configs/templates/conditions/pmel_geofence.json
      - ../../shared_configs/templates/conditions/cn_limit.json
      - ../../shared_configs/templates/conditions/revpi1_telemetry_active.json
      - ../../shared_configs/templates/conditions/revpi1_power_states.json

nameSuffix: "-revpi1"

patches:
  - target:
      kind: Service
      name: sampling-conditions
    patch: |-
      - op: replace 
        path: /spec/template/spec/volumes/0/configMap/name
        value: sampling-conditions-conditions-revpi1
  - target:
      kind: Trigger
    patch: |-
      - op: replace 
        path: /spec/subscriber/ref/name
        value: sampling-conditions-revpi1

configurations:
  - config.yaml