apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: datastore-sensor-data-update
  # namespace: msp-events
spec:
  broker: default
  filter:
    attributes:
      type: envds.data.update
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: datastore
      # namespace: msp-system
    uri: /sensor/data/update
