apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: datastore-device-definition-registry-ack
  # namespace: msp-system
spec:
  broker: default
  # filters:
  #   - any:
  #       - exact:
  #           type: envds.device-definition.registry.ack
  #   - exact:
  #       source: envds.payload03.datastore
  filter:
    attributes:
      type: envds.device-definition.registry.ack
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: kn-mqtt-adapter
      # namespace: msp-system
    uri: /mqtt/send


# apiVersion: eventing.knative.dev/v1
# kind: Trigger
# metadata:
#   name: datastore-device-data-update
#   # namespace: msp-events
# spec:
#   broker: default
#   filter:
#     attributes:
#       type: envds.data.update
#   subscriber:
#     ref:
#       apiVersion: serving.knative.dev/v1
#       kind: Service
#       name: datastore
#       # namespace: msp-system
#     uri: /device/data/update
# ---
# apiVersion: eventing.knative.dev/v1
# kind: Trigger
# metadata:
#   name: datastore-sensor-settings-update
#   # namespace: msp-events
# spec:
#   broker: default
#   filter:
#     attributes:
#       type: envds.sensor.settings.update
#   subscriber:
#     ref:
#       apiVersion: serving.knative.dev/v1
#       kind: Service
#       name: datastore
#       # namespace: msp-system
#     uri: /device/settings/update
# ---
# apiVersion: eventing.knative.dev/v1
# kind: Trigger
# metadata:
#   name: datastore-device-settings-update
#   # namespace: msp-events
# spec:
#   broker: default
#   filter:
#     attributes:
#       type: envds.device.settings.update
#   subscriber:
#     ref:
#       apiVersion: serving.knative.dev/v1
#       kind: Service
#       name: datastore
#       # namespace: msp-system
#     uri: /device/settings/update
# ---
# apiVersion: eventing.knative.dev/v1
# kind: Trigger
# metadata:
#   name: datastore-device-definition-registry-update
#   # namespace: msp-events
# spec:
#   broker: default
#   filter:
#     attributes:
#       type: envds.device-definition.registry.update
#   subscriber:
#     ref:
#       apiVersion: serving.knative.dev/v1
#       kind: Service
#       name: datastore
#       # namespace: msp-system
#     uri: /device-definition/registry/update
# ---
# apiVersion: eventing.knative.dev/v1
# kind: Trigger
# metadata:
#   name: datastore-device-registry-update
#   # namespace: msp-events
# spec:
#   broker: default
#   filter:
#     attributes:
#       type: envds.device.registry.update
#   subscriber:
#     ref:
#       apiVersion: serving.knative.dev/v1
#       kind: Service
#       name: datastore
#       # namespace: msp-system
#     uri: /device/registry/update