serial_number: "optics"
daq_id: payload02
modbus_address: 1
interfaces:
  default: # to read PV and write SV via serial-to-TCP gateway
    interface_env_id: payload02 
    interface_id: USconverters::USCDR301::usc_optics # UPDATE THIS to your actual interface ID
    path: port-1 # UPDATE THIS to match your target COM port mapping
settings:
  set_value: 25.0