apiVersion: v1
kind: ConfigMap
metadata:
  name: shelly-shellypro2-config
  # namespace: msp
  labels:
    app: shelly-shellypro2
data:
  namespace_prefix: mspbase01
  envds_env_id: mspbase01
  controller.conf: |
    uid: shelIP
    host: AddIP
    client_host: mqtt.mspbase01-system
    client_port: 1883
    controller_id_prefix: shellypro2

    # override definition values
    attributes:
      serial_number: shelIP
    # variables:
    #   channel_2_power:
    #     default_value: "0"
