apiVersion: v1
kind: ConfigMap
metadata:
  name: system-modes
  # namespace: msp-system
data:
  daq_id: payload01
  port: "8080"
  knative_broker: "http://broker-ingress.knative-eventing.svc.cluster.local/payload01-system/default"

  system_init_control: "auto"
  system_init_mode: "normal"
  is_primary_controller: "false"

  SYSTEM_MODES_DEPLOYMENT_REF: "deploy.pmel.payload_01_in_msp_01"
  
  mqtt_broker: "mqtt.payload01-system"
  mqtt_topic_subscriptions: >
    envds/+/+/+/data/#,
    envds/+/system-modes/#,
    envds/+/sampling-modes/#


  mqtt_port: "1883"
