
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-pvc
  namespace: msp-system
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi