apiVersion: v1
kind: ConfigMap
metadata:
  name: vaisala-aqt560-config
  # namespace: msp
  labels:
    app: vaisala-aqt560
    app-group: envds-sensor-mspbase02
data:
  namespace_prefix: mspbase02
  envds_env_id: mspbase02
  sensor.conf: |
    serial_number: "908"
    daq_id: mspbase02
    interfaces:
      # default: serial
      default:
        interface_env_id: mspbase02-hardware # if omitted, defaults to envds_id of sensor
        interface_id: USconverters::USCDR301::usc206
        path: port-1
      #   connection-properties:
      #     baudrate: 115200
      #     bytesize: 8
      #     parity: N
      #     stopbit: 1
      #   # read-properties:
      #     read_method: "readline" # default
      #     # terminator: "\r"
      #     # binary: true
      #     # num-bytes: 1
      #     # decode-errors: strict
      # # power: # example of second interface (e.g., CDP enable signal)
      # #   interface_id: system::mock::localhost
      # #   path: port-01
      
    # settings: # used to override defaults
    #   pump_power: 1
    #   q_target: 300