apiVersion: v1
kind: Service
metadata:
  name: dwyer-scd1000
  labels:
    app: dwyer-scd1000
spec:
  selector:
    app: dwyer-scd1000
  ports:
  - name: http
    protocol: TCP
    port: 9080
    targetPort: 9080
  type: ClusterIP