apiVersion: v1
kind: ConfigMap
metadata:
  name: sampling-states
data:
  daq_id: payload02
  SAMPLING_NAMESPACE: "pmel.noaa.gov"
  ENVOPS_DEPLOYMENT_REF: "deploy.pmel.payload_02_in_msp_01"
  STATES_REVISION_TIME: "2026-06-11T19:31:00Z"

  port: "8080"
  knative_broker: "http://broker-ingress.knative-eventing.svc.cluster.local/payload02-system/default"
  mqtt_broker: "mqtt.payload02-system"
  mqtt_topic_subscriptions: "envds/+/sampling-conditions/status/update"
  mqtt_port: "1883"

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: sampling-states
#   # namespace: msp-system
# data:
#   daq_id: payload02

#   ENVOPS_DEPLOYMENT_REF: "deploy.pmel.payload_02_in_msp_01"

#   port: "8080"
#   knative_broker: "http://broker-ingress.knative-eventing.svc.cluster.local/payload02-system/default"

#   mqtt_broker: "mqtt.payload02-system"
#   mqtt_topic_subscriptions: >
#     envds/+/sampling-conditions/status/update

#   mqtt_port: "1883"

# # off
#     # envds/+/+/+/data/update,   
#     # envds/+/+/+/controller/data/update   
