apiVersion: v1
kind: ConfigMap
metadata:
  name: ist-hyt271-config
  # namespace: msp
  labels:
    app: ist-hyt271
    # app-group: envds-sensor-payload03
    app-group: envds-sensor-crk8s
data:
  namespace_prefix: mspbase01
  envds_env_id: mspbase01
  # namespace_prefix: crk8s
  # envds_env_id: crk8s
  sensor.conf: |
    serial_number: "1234"
    daq_id: mspbase01
    # daq_id: crk8s
    interfaces:
      # default: serial
      default:
        interface_env_id: cloudy # if omitted, defaults to envds_id of sensor
        interface_id: NetBurner::SB70LC::nb53
        # interface_id: NetBurner::SB70LC::home38
        # path: port, channel, etc
        path: port-I2C
