apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: filemanager

# set namespace
namespace: payload02-system

resources:
  - ../../base
  - filemanager-configmap.yaml
  # Comment the line below out if you ONLY want MQTT ingestion on raz1 right now
  # - filemanager-triggers.yaml 

# Ensure the config map overrides any dummy config in the base
configMapGenerator:
  - name: filemanager-config
    behavior: merge
    files:
      - filemanager-configmap.yaml