apiVersion: v1
kind: ConfigMap
metadata:
  name: shelly-shellypro1-config
  # namespace: msp
  labels:
    app: shelly-shellypro1
data:
  namespace_prefix: payload01
  envds_env_id: payload01
  controller.conf: |
    uid: shel227
    host: 10.55.179.29
    client_host: mqtt.payload01-system
    client_port: 1883
    controller_id_prefix: shellypro1-physics

    # override definition values
    attributes:
      serial_number: shel29
    # variables:
    #   channel_2_power:
    #     default_value: "0"
