apiVersion: v1
kind: ConfigMap
metadata:
  name: sampling-modes
  # namespace: msp-system
data:
  daq_id: pmel-dev

  ENVOPS_DEPLOYMENT_REF: "deploy.pmel.msp_enclosure_01_at_marina"
  
  port: "8080"
  # knative_broker: "http://broker-ingress.knative-eventing.svc.cluster.local/pmel-dev-system/default"
  knative_broker: "http://kafka-broker-ingress.knative-eventing.svc.cluster.local/pmel-dev-system/default"
  
  is_primary_controller: "false" # ADD THIS LINE

  mqtt_broker: "mqtt.pmel-dev-system"
  mqtt_topic_subscriptions: >
    envds/+/+/+/data/#,
    envds/+/sampling-states/#,
    envds/pmel-dev/sampling-modes/#


  mqtt_port: "1883"
