apiVersion: apps/v1
kind: Deployment
metadata:
  name: acoem-aurora3000
  # namespace: msp
  labels:
    app: acoem-aurora3000
spec:
  selector:
    matchLabels:
      app: acoem-aurora3000
  template:
    metadata:
      labels:
        app: acoem-aurora3000
    spec:
      imagePullSecrets:
        - name: ghcr-ro-secret
      containers:
      - name: acoem-aurora3000
        # image: registry-msp:5000/msp/sensor/acoem-aurora3000:0.1.0
        image: ghcr.io/noaa-pmel/msp/acoem-aurora3000:0.1.0
        imagePullPolicy: "Always"
        env:
          - name: ENVDS_CORE_NAMESPACE_PREFIX
            valueFrom:
              configMapKeyRef:
                name: acoem-aurora3000-config
                key: namespace_prefeix
          - name: ENVDS_ENV_ID
            valueFrom:
              configMapKeyRef:
                name: acoem-aurora3000-config
                key: envds_env_id
          - name: REDIS_OM_URL
            value: redis://redis.default
          - name: LOG_LEVEL
            value: DEBUG
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 9080
          protocol: TCP
        # - name: https
        #   containerPort: 8883
        #   protocol: TCP
        volumeMounts:
            - name: acoem-aurora3000-config
              mountPath: /app/config/sensor.conf
              subPath: sensor.conf
            - name: sensor-definition
              mountPath: /app/ACOEM_Aurora3000_sensor_definition.json
              subpath: ACOEM_Aurora3000_sensor_definition.json
      volumes:
        - name: acoem-aurora3000-config
          configMap:
            name: acoem-aurora3000-config
        - name: sensor-definition
          configMap:
            name: sensor-definition
