apiVersion: apps/v1
kind: Deployment
metadata:
  name: shelly-shellymock
  # namespace: msp
  labels:
    app: shelly-shellymock
spec:
  selector:
    matchLabels:
      app: shelly-shellymock
  template:
    metadata:
      labels:
        app: shelly-shellymock
    spec:
      imagePullSecrets:
      - name: ghcr-ro-secret
      containers:
      - name: shelly-shellymock
        # image: registry-msp:5000/msp/interface/shelly-shellymock:0.1.0
        image: ghcr.io/noaa-pmel/msp/shelly-shellymock:0.2.0
        imagePullPolicy: "Always"
        env:
          - name: ENVDS_CORE_NAMESPACE_PREFIX
            valueFrom:
              configMapKeyRef:
                name: shelly-shellymock-config
                key: namespace_prefix
          - name: ENVDS_ENV_ID
            valueFrom:
              configMapKeyRef:
                name: shelly-shellymock-config
                key: envds_env_id
            # value: mspbase01
          - name: REDIS_OM_URL
            value: redis://redis.default
          - name: LOG_LEVEL
            value: DEBUG
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 9080
          protocol: TCP
        # - name: https
        #   containerPort: 8883
        #   protocol: TCP
        volumeMounts:
            - name: shelly-shellymock-config
              mountPath: /app/config/controller.conf
              subPath: controller.conf
            - name: controller-definition
              mountPath: /app/Shelly_ShellyMock_controller_definition.json
              subPath: Shelly_ShellyMock_controller_definition.json
            # - name: mosquitto-certs
            #   mountPath: /certs/ca.crt
            #   subPath: ca.crt
            # - name: mosquitto-certs
            #   mountPath: /certs/server.crt
            #   subPath: server.crt
            # - name: mosquitto-certs
            #   mountPath: /certs/server.key
            #   subPath: server.key
      volumes:
        - name: shelly-shellymock-config
          configMap:
            name: shelly-shellymock-config
        - name: controller-definition
          configMap:
            name: controller-definition
        # - name: mosquitto-certs
        #   configMap:
        #     name: mosquitto-certs
