apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampling-modes
  labels:
    app: sampling-modes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampling-modes
  template:
    metadata:
      labels:
        app: sampling-modes
    spec:
      imagePullSecrets:
      - name: ghcr-ro-secret
      containers:
        - name: sampling-modes
          image: ghcr.io/noaa-pmel/msp/sampling-modes:0.5.0
          imagePullPolicy: "IfNotPresent"
          
          # This natively injects SAMPLING_NAMESPACE, ENVOPS_DEPLOYMENT_REF, etc.
          envFrom:
            - configMapRef:
                name: sampling-modes
                
          # Explicit mappings required by your pydantic BaseSettings
          env:
            - name: SAMPLING_MODES_PORT
              valueFrom:
                configMapKeyRef:
                  name: sampling-modes
                  key: port
            - name: SAMPLING_MODES_DAQ_ID
              valueFrom:
                configMapKeyRef:
                  name: sampling-modes
                  key: daq_id
            - name: SAMPLING_MODES_MQTT_BROKER
              valueFrom:
                configMapKeyRef:
                  name: sampling-modes
                  key: mqtt_broker
            - name: SAMPLING_MODES_MQTT_PORT
              valueFrom:
                configMapKeyRef:
                  name: sampling-modes
                  key: mqtt_port
            - name: SAMPLING_MODES_MQTT_TOPIC_SUBSCRIPTIONS
              valueFrom:
                configMapKeyRef:
                  name: sampling-modes
                  key: mqtt_topic_subscriptions
            - name: SAMPLING_MODES_KNATIVE_BROKER
              valueFrom:
                configMapKeyRef:
                  name: sampling-modes
                  key: knative_broker
            - name: SAMPLING_MODES_IS_PRIMARY_CONTROLLER
              valueFrom:
                configMapKeyRef:
                  name: sampling-modes
                  key: is_primary_controller
                  optional: true
          
          volumeMounts:
            - name: sampling-modes-modes-vol
              mountPath: /app/config/modes
            - name: sampling-modes-actions-vol
              mountPath: /app/config/actions

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 10
            periodSeconds: 10
            
      volumes:
        - name: sampling-modes-modes-vol
          configMap:
            name: sampling-modes-modes
        - name: sampling-modes-actions-vol
          configMap:
            name: sampling-modes-actions