apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: sampling-modes-action-definition-update
spec:
  broker: default
  filter:
    attributes:
      type: envds.action-definition.registry.update
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: datastore
    uri: /action-definition/registry/update/
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: sampling-modes-samplingmode-definition-update
spec:
  broker: default
  filter:
    attributes:
      type: envds.samplingmode-definition.registry.update
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: datastore
    uri: /samplingmode-definition/registry/update/
