apiVersion: v1
kind: Service
metadata:
  name: pmel-erddap
  # namespace: msp-system
  labels:
    app: pmel-erddap
spec:
  selector:
    app: pmel-erddap
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
    # - name: https
    #   port: 443
    #   targetPort: 8043
  type: ClusterIP  