apiVersion: v1
kind: Service
metadata:
  name: erddap
  # namespace: msp-system
  labels:
    app: erddap
spec:
  selector:
    app: erddap
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: https
      port: 8043
      targetPort: 8043
  type: ClusterIP  