apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-ro-secret
  namespace: mspbase02-system
spec:
  encryptedData:
    .dockerconfigjson: AgCFHqXMeUhLWsZgRe2EN/W4SMRiquhFoui1g0HnZGo8myzTrpi20IzVX+AyvEWTDsC1fcQiTWdyiF6FiULTzvRiuCe5p7RHJoZOvzxPJB42vDVOCUuoeKVeZ0pJRRStSgUksRomhW8qxkyBZAFtUlG8BHgJYFE0ezuw06MUKNOlIKw0GK/bYY0ecvyO98qXb5SHyNNuuuSnLLZwbFN+oMMmS37kcHNJdX49NaDdjnEysacvbfMOZz3EQ/EFyt/gShWjtPg6CJuVHCukoKTo+ulFwhpqSqU4IRg489jbgwyWixLs4ZTSXiCyV55LU3i7dQcoIXJgEG1Bako78iECZzofG22Z0ZY48/QJJm7qyunGcWe3s56ABovtrF9Tv5FBr+l/lNfRfSV7PWB4/FjQJJAqQCrxt6XKYY0RpByxQBPiFZ/tcxSg4TkK0Qx8Usf06kxRZAi+POjckfhjoiJ4CWnbKJ1U9wJarOYgTBEKTBIZjjCt8ZwUQYG01DmdH5Nlqw4XrOpydL5wOAJQW+9Jn9gGcmpw1RiUEyU/d/isUN+3wmDAz6LmYDLt67LpIL1xu/uoCH9Cw2VexY3TYl9FcDstDjsrv+djngRkQF1Oy4ha9mM4viKHGdrXeqUKNFRN5PuLHB7uWJeLjSGWT8Ryj+cSTv+gfa2pDqZTfp7E6mtUDxZK9DhqZ3ezv++CGr00Wd1XLLKPthgsKKAhTOCH7SWpG+kj1LkToAndjUAnXYzycJR8qH2CM3qLFqqTHrEUytoTB70vGXpdJ1wX5c2tGlpNIlqfkCboVU7LvTEvQm76VjkUzqySDKGrie9W7qK/Jr0PQ/hY2uLUnjixkf1WcApqz4+jCpS6DoGGYK+UtjKJ0wn4tDL+RppUPkIuw5nA2na266JT3We6oIn1zkbUugWDy1xg/tIg1qg3EacLgbKRzBcHJH6Yl1VBxDV82fdQRujt+fcYQ8KQDFeAECwYrLxkBm0fC9E9qRF2NGsYWutVHfhZAA==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-ro-secret
      namespace: mspbase02-system
    type: kubernetes.io/dockerconfigjson

