---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datastore-db=password
  namespace: crk8s-system
spec:
  encryptedData:
    db_password: AgBxxrAwuohBFPOq3xUJa2WxUXIXwLIPI+4CUhC2bzIi2VOO/2/HQD+UOskgEYv4hZ1kFYo+tFPiMJ+oL6tOxQAoZv/HmaZqgftVx1boElkOaagZ2uI+spIjvnfp745doe8Jev1sCvw8zfON2+HWYeFy09ZZudWvgbBV8iLjVfPKHr8GsRiSjHwJ0r214Ar7mI8XYzzG7y7GEFHaR7gtrMMuY6NdvldKlMsQpawYGqhvprvwGjK+XS/N/CL3F7RJIz1MKE+hIHFiT5dsszT+pwGK/yxCrW4Dhcn9dyk8H/5Fj+XHw6PrE/TIKx8ojzrrn5qcfRANJ7yoC6a8wUju7olknr3i0Tadank1n7e2gFCmQSJvDRelmkpnUFfddtjd3CUdZaLeQ4nszIOJPMzoY67dLRIUq726mmvh9FDZ/DNoKYh8Obqaf3AEE3SYbfBLZ2/oRs1N9ZcxCzIr1mFpKHSiGApcxko9a1mykGiWpszCrIpnZU5oOlwguDtqIpIFJxVF0lAQA9SGFwUUXLPHLJj44zmQftUv+ootsbyGkOY2QIkWqP49Gh2uvJx9AAXQRtu894qdcQ9eAKeiX2/CuyCkXMlI0/ipFlw0WCXGjfFan/5vRN+8tkUSZzde5j+zc9Z1wd4WtHluWTgkh9SaopAeDQIIC1Qces+b7LRISJMTjqRtPnT9g8ae51IvpY/3IwGjV9cfFQ==
  template:
    metadata:
      creationTimestamp: null
      name: datastore-db=password
      namespace: crk8s-system
