apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ist-hyt271

# Example configuration for the webserver
# at https://github.com/monopole/hello
# commonLabels:
#   app: nginx

resources:
- hyt271-deployment.yaml
- hyt271-service.yaml

configMapGenerator:
  - name: sensor-definition
    files:
      - IST_HYT271_sensor_definition.json