apiVersion: v1
kind: ConfigMap
metadata:
  name: labjack-tx-config
  # namespace: msp
  labels:
    app: labjack-tx
data:
  namespace_prefix: payload02
  envds_env_id: payload02
  interface.conf: |
    uid: ljtx31
    attributes:
      host: 10.55.179.31
      model: T4
    paths:
      i2c:
        path_type: I2C
        sda_channel: 5
        scl_channel: 4
        speed_throttle: 65516
      counter-16:
        path_type: COUNTER
        channel: 16
        counter_mode: "interrupt"
        sample_mode: "unpolled"
        unpolled_interval_handle: 2
        unpolled_sample_frequency_sec: 1
      counter-18:
        path_type: COUNTER
        channel: 18
        counter_mode: "interrupt"
        sample_mode: "unpolled"
        unpolled_interval_handle: 3
        unpolled_sample_frequency_sec: 1
      pwm-6:
        path_type: PWM
        pwm_channel: 6
        clock_channel: 1
        clock_divisor: 1
        clock_desired_frequency: 15000
        counter_mode: "interrupt"
      pwm-7:
        path_type: PWM
        pwm_channel: 7
        clock_channel: 2
        clock_divisor: 1
        clock_desired_frequency: 25000
        counter_mode: "interrupt"
      # voltage_in-0:
      #   path_type: ADC
      #   channel: 0
      #   input_voltage_range: 1.0
      #   input_type: "single"

# tmp
      # voltage_in-1:
      #   path_type: ADC
      #   channel: 1

