apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: vaisala-wxt536


namespace: mspbase01-hardware

# Example configuration for the webserver
# at https://github.com/monopole/hello
# commonLabels:
#   app: nginx

# resources:
# # Example configuration for the webserver
# # at https://github.com/monopole/hello
#   nameSuffix: -usc206
#   commonLabels:
#     app: usconverters-uscdr301
#     variant: test

resources:
- ../../base
- wxt536-configmap.yaml

nameSuffix: "-908"
# patchesStrategicMerge:
#   - deployment.yaml