apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: sanyodenki-sanace92rf


namespace: mspbase01-hardware
# namespace: crk8s-hardware

# Example configuration for the webserver
# at https://github.com/monopole/hello
# commonLabels:
#   app: nginx

# resources:
# # Example configuration for the webserver
# # at https://github.com/monopole/hello
#   nameSuffix: -usc206
#   commonLabels:
#     app: usconverters-uscdr301
#     variant: test

resources:
- ../../base
- sanace92rf-configmap.yaml

nameSuffix: "-inletflow"

# patchesStrategicMerge:
#   - deployment.yaml

patches:
  # change configmap names to account for s/n suffix
  - target:
      kind: Deployment
      name: sanyodenki-sanace92rf
    patch: |-
      - op: replace 
        path: /spec/template/spec/volumes/0/configMap/name
        value: sanyodenki-sanace92rf-config-inletflow
      - op: replace 
        path: /spec/template/spec/volumes/1/configMap/name
        value: operational-definition-inletflow
