serial_number: "inletflow"
daq_id: mspbase02
interfaces:
  default: 
    interface_env_id: mspbase02 
    interface_id: LabJack::Tx::ljtx226 
    path: counter-18
  fan_speed_sp: 
    interface_env_id: mspbase02 
    interface_id: LabJack::Tx::ljtx226 
    path: pwm-6

settings:
  fan_speed_sp: -80