apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telemetry-proxy-secret
  namespace: revpi1-system
spec:
  encryptedData:
    encryption_key: AgCqLc/s1LUYqn7LwikY/+kUD4s1uArl6IAUH9+gCEhvisLBrdQts8l3XPffSmzIJBDr/4KVWf8xRDRL5TelzuXIQ0ZrFMkLIonQL+lFUSe+XXCgzD74AlRna5dayRKUV/ZhsAe3ATOWwNI8gQr5L9gl9r8d0+PnMmnGxHSlCedqlVHD9ygPNj1ceOzYpZLmABWD3B211MDaTnD57Ovhgk+iBiFAQctOvoir9g4yuZxpWXUWqxNxAw/2SYTQ1JWhh8QuTj2LyX8330XKb4jLkqHSUWzjWAck7kWbeIIMCp2yy5PgA9d4G3wNEvUbR/QhqIdzLkd7Yx8Pvyt8gk9R0iuMv1f7c6lvs7jZbMCTIMdg0sJ2/7dYWI3AU5qd/6a3gy8p3SKSMwV53EfOm5raFYSDK/3xuRoMufZ+pEz3fOAkk5BBniz16AFj7EhLJ2AqFbd2KpNoyaWtkknt1KOrlniekdmv7YYIp8gLHz9JZ3cS2xJrXyEZxGu2vepSF+tU37Q5l1G54MfgJhN5Jo2fvA+0zNcGNPEDeaSJPa490CPDBFeRlnShdBcIwIdBdkETJU6re/5Olnkh9xC2jA7Gy/VSQBDQPAlzwZjlyb0M2HVd6o6UVpNzFnxWik1ahtQwS1YlIcvsdceMQQDnU1fOvSTKCQbPDM2zq1GgMtSL8MEtqTm5sj8koyYiTL7r9mpetJUnmJ+J8i1W8sKg7BsKDkUBem++54EDVL72xgWIrkTTvw==
  template:
    metadata:
      creationTimestamp: null
      name: telemetry-proxy-secret
      namespace: revpi1-system

