apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-ro-secret
  namespace: payload03-system
spec:
  encryptedData:
    .dockerconfigjson: AgBZQXWVvejNNC3pDoaTWFew3rd2+fqJJ1AS/jtyX7AS6ORaS39Ah/kkWWS6N0rROcD0/9odr3n5MqUG3VhrrSIina1SoU4sMez8jN3T6yKSg8Ur0kSdiG2kN3MOxtrYmESvBbw6Q8WOEJ/TTwsLZqzJ6lto4vTcGcPBdjy/A2vFn25kE8Ws6xnGAuqd2UoHFGVj8y84rF+jOWQxtAiYD+PT2P/i+mt8Vvc1aWLXd+gf0KzFU7YqOU93bwGi/abrzuevfsEOuJmmR+ntQxpI5ID7reKyCROLxM5/rOrgGsFB3OGayzC+EZ9tzoLHD3wP70jORW+K1xupNHzgqXfnM/yzBFUpWv7v8DLg7Yb9MiOLD9OnwXwnPvujGakiXGd1HCsIyJKP4vXCnnNItw5PRziB61+hZTI8i77nlHvq0nSLP6RmC33TPkHlGVTR/o1BXdTyfv+bb1NvNiKKNA7Kg89TnIhBB2WL8lUszcTiEmpGAWoROcjTjvtut/mwrJw+vm2rlDx35JRUQZSMxins3tkkQm2UyIi6a0qYEqL+YYpzSxCfMEGwxfl69Ij0jKJ1xbjkSc7ugcITEDZ6edwbbjaHdlif7RJNX7drlazDhJArmJxjBY+EXY5OepvqQ9mfE0LUJWId7plV++rUMGTpgkLxQqyyqo4NNQLkL4JlyuBdwATGbGeuZTY/vqexLoJJ7ThTyQ+1jTN/gPaXiB38tObRuke5y9njEjJ9ybapSlcbchOaGIEt+U+uKb2BoARhmWwlUjAS/Cf8ssZE+HLiN3y3G7BDoKuYyss9qQE6Nv55TcLYBlqmb2g4Y807m0jp3r6bYQc1oj/4Cnq1yhy1fSi9dhKHIhehUM/ySzPPx7+DD0UxFG3t3LnnMF9gEYioYvDqZis6R7WgYIemIG90KjnGoqqmSqXd9bRwSF/XupaDaYxDnDprfe8NAF1uJ0P0fe1lnv04y8WrJI9eV42BfXNnX7QUwhBwCKiEi6LQUEg04/YbSA==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-ro-secret
      namespace: payload03-system
    type: kubernetes.io/dockerconfigjson

