apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-ro-secret
  namespace: payload03-system
spec:
  encryptedData:
    .dockerconfigjson: AgAvf1zadHxvLEcmcFPrx5Bl8qSaM5q6k2S5ZNLS4jXiuzo+BnGN6Va9D8pTZ8oTC6kwGQcMrohlG/a5Hrp1tLLLJ89372Wdeq1fl5zcB8qhQv/bxHpilTQhjGasFb/MQCrFhQxnLtYMe9r7w48pyv1P0Xv3jkp+3oRCHjj58zhodNGaMSfzqbdYhf9+E58y67WNLDa26JnS9AzhTSfhp0G0xt5JJyX/FuCkifPqk95WQeF55DUGx+f/zxi3D4WkFH05MFKwG17s9pwGmRfYeNfzjgUi9KPATGdA7YH6eEHr8bIN6OqpexJTQfx14eyxRHUtdDcwnMkcWdzIIYT0o3USLQ3nzcHWYWHzEmz6oyedOXWPvZGxeory4nWGZKv5EtGqtne/PCiUHu11oRSLAvOCDg0lijM09UGgs9Vwo8ombxc0Wcb+6FCI8SeLwuIi5sAo61nPWSI5Xq2Lne1NTzR73olNkMPoBXM8bAnCt9ABjn6JJFCclZ8EH1tGJJC+QgBhqhf7FmSErHM5eJxMVpcF4cmJQbemYhJnaU37F+71SyaE9lJGR1NLLrh6/IEH/4vfYlIlr0ia0QHYybZi77D6VrWqyLjXxa1zXGT+wHhYTHdf3opk72UToZrxmOMhR4L4IeUaUnUDEbKGMhbukj4n5h0z2eD3k96G3IzwcWEmpLale+1tmRbJ/TypPns46TE1314RG4DcHcxJ+B92PoO9L5IcxmEVYaMSRw7dMFxmRMiAcYbbIbdPeRDK1dF7iYOv+YBDWDoKeYHCibHKd25mSk20LZ8QF0YA5y6ATrxsX2y+lMvBgG95pXj+7vR3qCBLPuWtwNjk98twBLtWGdIShg+/3TgNBzPrHiamfXAoFo4U3c3QV1yu8PRTW6oQiKZDLJ/kBWHPguSzujWAeTYq
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-ro-secret
      namespace: payload03-system
    type: kubernetes.io/dockerconfigjson

