apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  # namespace: msp-system
  # labels:
  #   type: local
spec:
  storageClassName: gp2
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  # hostPath:
  #   path: "/data/msp/data/redis/mspbase02"