apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  # namespace: msp-system
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: redis-pv