apiVersion: v1
kind: Service
metadata:
  name: tsi-aps3321
  # namespace: msp
  labels:
    app: tsi-aps3321
spec:
  selector:
    app: tsi-aps3321
  ports:
  - name: http
    protocol: TCP
    port: 9080
    targetPort: 9080
  # - name: https
  #   port: 8883
  #   targetPort: 8883
  # type: LoadBalancer
  type: ClusterIP