apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-ro-secret
  namespace: raz1-system
spec:
  encryptedData:
    .dockerconfigjson: AgAn+f67vzmtxYsaBcuQ3cimLwr8/JyQBIeVfGETmYS/8kr58XZx25/ymDpkHIsmeOQM8jzwbltKTJDNzr4v1t0kut2BMTh7FDukzuZmFeeZP7MZaSxMPZK+B4ZV7igf1X/aDd9PVcC8FSDbVQ/ZfH+crVahd2wMXnKfwoYiCACuBORX8wdHDBibF81roFEfwz83Y586Gb+2HonzzyFcUtH9xtJC1mIAuzk9siysor7UaDTQYrf3V6VD5wYlicPPq7muqo3n17gTVfHbYvxaGMJ7UuSGj4IYYPNym/P81UbjAu93c2OA30EjirnVu5kGYnac47Z5c7ycoTjARs831TFTaNldx8xxUN5Qh+GvVNrHnn+rrXEteVtEakYO5uIr1Bsp5o0zpuRJPzXn2qmw+YiORW2Ua0YncMrQ0zfaaKl9L0/vEVlgOHhl7282upxjDySZyOqJtI09z7hG5ffrI4wLMxqFr6kkHtEM9XHpgQqlcf/4/bgU8JUCwv8PaqjboBnb/KcX9++q86GaI1HuxctltsjImrupGnzd3LNWnpTsDcK77U1RBou/6ptSW77XQiH2FvKkXqphGSP2nzzG9ixgXdITIiZ0xZoJI/362JT71Q0bvG0vwluJStjfUv6cGtHZsDwxabi9Gs/lf+U68iqMcEYQCF0bDFYXtb/gmn4I+bbjz6MBvSNhHiH5OcBddZc2RBTOj++gm6u+JVkCv63pTv4KtXDn9j6iP+S34UvM6xy72TxjFtb6dAjUVf9FcTk5P+CmK8K3R23TRhtSZwqf6SbZn0DKcTdt430U6WH3CqVVarEg0nx4iqatPadNtcWHdHG6JzVb+qIglW5BP0TRntQ4HKAvoufvYmNGL5xCf02uZqlfnR+8L/o9WnBIVaHQLUPhABCy7E8llYg52YDx
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-ro-secret
      namespace: raz1-system
    type: kubernetes.io/dockerconfigjson

