apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-ro-secret
  namespace: raz1-hardware
spec:
  encryptedData:
    .dockerconfigjson: AgBGmjo0pbZ/vrQFCyk4vmp+SoH6iQUmPvrY0fFEjMejhDeBZL6NYPk5GWC9nfP2FjptVVvy/ecppqKNIDVAH7M5U3maBow7uQTUAuI7KdepKpX2cxdtkJCv7Fuprs+1IeVnyqP+Eey1Jsh6WXZInK659MvM0fS30hHadjvpFCKMW7zfRX/L9fNYnuQ45nGMlYQwQeoCiwl0sZDU5/otJSkqfUYHe0d17853OS+vmLtmnjVKJ3R0KtFbS51IxofSl+fVBDbO1J8nYPstjq+OLr9mfZkUKbONOaTCW6iB7PCriojFjzqvzHjVoESQ5G4syjhA/RbgyoBO2Yh+y7BnOcsSHTyEFmVuLjxxuEH9SFgxnm7bjDofDVGiKUvMp9u9apR0ugUd4f3DBZXutIrlwAAEXQ1DbI41ag8qBSjMylzGWIncyhV+mRVYOMkOhYoPRnXKe29mRflB3FAD/60AHtyyza4OTFzVo0b7dBVhqM5EslF9CHU94TFOh19KimD6/KtrIBwm6xMCBAs17Te3u1IqhTuncHirBtQFA4gjvx8zBwQSKBwhzzBoIERkxJ9H63bRJZNn33ScGBYrzdgnvVssbzb0jg3+lFe5AkBMnHHRkdf+Bc+H/plqPz4KTVFy3Q/XqDEAVHQmdiz2IKe7AiGGh2LqMUSoHGWNPV2KGdhqGdg2LuWKGo3i4LAgJw6UN20aHKZMeQTy18rJnsCZpnzpUkdpLXRkyr+4CJCKLIyzueFvmo6TgjksYD8ZH4j2bykuXfrloGL0sIBmmeGtEuFffh4NWx8R/tlIXrYt/7IYX7d4qkoiPNkHbFfl2OcP638nol5z1mRYo9uD7GENONQ4CnfF+xmH8KKMYzl9T6ebJnhmcxuduoaplwDKbjcjZ9V88k06SXPd4evaPFfGYYIp
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-ro-secret
      namespace: raz1-hardware
    type: kubernetes.io/dockerconfigjson

