apiVersion: v1
kind: ConfigMap
metadata:
  name: sampling-conditions
  # namespace: msp-system
data:
  daq_id: raz1

  ENVOPS_DEPLOYMENT_REF: "deploy.pmel.payload_03_in_msp_01"

  port: "8080"
  knative_broker: "http://broker-ingress.knative-eventing.svc.cluster.local/raz1-system/default"

  mqtt_broker: "mqtt.raz1-system"
  mqtt_topic_subscriptions: >
    envds/+/variableset/+/data/#

  mqtt_port: "1883"

# off
    # envds/+/+/+/data/update,   
    # envds/+/+/+/controller/data/update   
