apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payload01-system

resources:
  - ../../base

configMapGenerator:
  - name: sampling-states
    envs:
      - sampling-states.env
  - name: sampling-states-states
    files:
      - ../../shared_configs/templates/states/opc_power_stabilized_state.json
      - ../../shared_configs/templates/states/smps_power_stabilized_state.json
      - ../../shared_configs/templates/states/cpc_power_stabilized_state.json
      - ../../shared_configs/templates/states/aps_power_off_stabilized_state.json
      - ../../shared_configs/templates/states/cpc_power_off_stabilized_state.json
      - ../../shared_configs/templates/states/smps_power_off_stabilized_state.json
      - ../../shared_configs/templates/states/maintenance_active_state.json

# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# namespace: payload01-system

# resources:
# - ../../base
# - sampling-states-configmap.yaml

# configMapGenerator:
#   - name: sampling-states-states
#     files:
#       # Use the fully decoupled state definitions
#       - ../../shared_configs/templates/states/opc_power_stabilized_state.json
#       - ../../shared_configs/templates/states/smps_power_stabilized_state.json
#       - ../../shared_configs/templates/states/cpc_power_stabilized_state.json
#       - ../../shared_configs/templates/states/aps_power_off_stabilized_state.json
#       - ../../shared_configs/templates/states/cpc_power_off_stabilized_state.json
#       - ../../shared_configs/templates/states/smps_power_off_stabilized_state.json
#       - ../../shared_configs/templates/states/maintenance_active_state.json

# generatorOptions:
#   disableNameSuffixHash: true

# nameSuffix: "-payload01"

# patches:
#   - target:
#       kind: Service
#       name: sampling-states
#     patch: |-
#       - op: replace 
#         path: /spec/template/spec/volumes/0/configMap/name
#         value: sampling-states-states-payload01
#   - target:
#       kind: Trigger
#     patch: |-
#       - op: replace 
#         path: /spec/subscriber/ref/name
#         value: sampling-states-payload01

# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# metadata:
#   name: sampling-states

# # set namespace
# namespace: payload01-system

# # Example configuration for the webserver
# # at https://github.com/monopole/hello
# # commonLabels:
# #   app: nginx

# # resources:
# # # Example configuration for the webserver
# # # at https://github.com/monopole/hello
# #   nameSuffix: -usc206
# #   commonLabels:
# #     app: usconverters-uscdr301
# #     variant: test

# resources:
# - ../../base
# - sampling-states-configmap.yaml
# # - platform_defs_configmap.yaml
# # - platform_varmaps_configmap.yaml
# # - ghcr-secret-msp-system-sealed.yaml
# # uncomment this if using knative for data updates
# # - sampling-states-triggers.yaml

# configMapGenerator:
#   - name: sampling-states-states
#     files:
#       - sampling_states.json

# nameSuffix: "-payload01"

# patches:
#   # change configmap names to account for s/n suffix
#   - target:
#       # version: serving.knative.dev/v1
#       kind: Service
#       name: sampling-states
#     patch: |-
#       # - op: replace 
#       #   path: /spec/template/spec/volumes/0/configMap/name
#       #   value: sampling-states-payload01
#       - op: replace 
#         path: /spec/template/spec/volumes/0/configMap/name
#         value: sampling-states-states-payload01

# configurations:
#   - config.yaml
