apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: sampling-system=variablemap-definition-update
spec:
  broker: default
  filter:
    attributes:
      type: envds.variablemap-definition.registry.update
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: datastore
    uri: /variablemap-definition/registry/update/
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: sampling-system=variableset-definition-update
spec:
  broker: default
  filter:
    attributes:
      type: envds.variableset-definition.registry.update
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: datastore
    uri: /variableset-definition/registry/update/
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: sampling-system=platform-definition-update
spec:
  broker: default
  filter:
    attributes:
      type: envds.platform-definition.registry.update
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: datastore
    uri: /platform-definition/registry/update/