apiVersion: apps/v1
kind: Deployment
metadata:
  name: envops
  labels:
    app: envops
spec:
  selector:
    matchLabels:
      app: envops
  template:
    metadata:
      labels:
        app: envops
    spec:
      imagePullSecrets:
      - name: ghcr-ro-secret
      containers:
      - name: envops
        image: ghcr.io/noaa-pmel/msp/envops:0.6.0
        imagePullPolicy: "Always"
        envFrom:
        - configMapRef:
            name: envops
        # env:
        # - name: ENVOPS_DAQ_ID
        #   valueFrom:
        #     configMapKeyRef:
        #       name: envops
        #       key: daq_id
        # - name: ENVOPS_PORT
        #   valueFrom:
        #     configMapKeyRef:
        #       name: envops
        #       key: port
        # - name: ENVOPS_EXTERNAL_HOSTNAME
        #   valueFrom:
        #     configMapKeyRef:
        #       name: envops
        #       key: external_hostname
        resources:
          requests:
            cpu: "250m"
            memory: "500Mi"
          limits:
            memory: "1Gi"
            cpu: "750m"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP