apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: usconverters-uscdr301

# Example configuration for the webserver
# at https://github.com/monopole/hello
# commonLabels:
#   app: nginx

resources:
#- USCDR301-configmap.yaml
- USCDR301-deployment.yaml
- USCDR301-service.yaml