apiVersion: apps/v1
kind: Deployment
metadata:
  name: usconverters-uscdr301
  # namespace: msp
  labels:
    app: usconverters-uscdr301
spec:
  selector:
    matchLabels:
      app: usconverters-uscdr301
  template:
    metadata:
      labels:
        app: usconverters-uscdr301
    spec:
      containers:
      - name: usconverters-uscdr301
        image: registry-msp:5000/msp/interface/usconverters-uscdr301:0.1.0
        imagePullPolicy: "Always"
        env:
          - name: ENVDS_CORE_NAMESPACE_PREFIX
            valueFrom:
              configMapKeyRef:
                name: usconverters-uscdr301-config
                key: namespace_prefix
          - name: ENVDS_ENV_ID
            value: mspbase01
          - name: REDIS_OM_URL
            value: redis://redis.default
          - name: LOG_LEVEL
            value: DEBUG
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 9080
          protocol: TCP
        # - name: https
        #   containerPort: 8883
        #   protocol: TCP
        volumeMounts:
            - name: usconverters-uscdr301-config
              mountPath: /app/config/interface.conf
              subPath: interface.conf
            # - name: mosquitto-certs
            #   mountPath: /certs/ca.crt
            #   subPath: ca.crt
            # - name: mosquitto-certs
            #   mountPath: /certs/server.crt
            #   subPath: server.crt
            # - name: mosquitto-certs
            #   mountPath: /certs/server.key
            #   subPath: server.key
      volumes:
        - name: usconverters-uscdr301-config
          configMap:
            name: usconverters-uscdr301-config
        # - name: mosquitto-certs
        #   configMap:
        #     name: mosquitto-certs
