apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-ro-secret
  namespace: payload01
spec:
  encryptedData:
    .dockerconfigjson: AgAMqFT0gT+3oq5qdkNRpmPJY/OVDOzo1oVfrA7vVPwZnNimvOVAtuy3un3PW8+IvwGQ6by22poLZMLxlO42OjpgsCoKqGuRClpjtt+ZqSY8mSTpbq0ANcUeQRUDlmu7ZEaC+YgzpLzDad2PfzDB/BgIgHO8SHrYwyXnOgSqhHnxuE8Hpn+1EfxOvgbOWwPobX9g2Zp4PBcLZgYJVQqfL5nyBtwDXre+PFg+EXmzHgNTP7Ex581lLkdgsF7s3GwSb73pVxSZAVtVpupBKoEN1NJN2srkdCW5s/Eq14dZqJIVTuhx5yeDeHcfURMJWW00euTD8I3ZecZ9CwsESbwtUMeU5dQbeb6iwyhmbut+HXKaA9/u8MTzGX1dhPDxKWTJX857SXK5Pb258wl6qCnI1TQQAXago2PEWXYknsgRtK6NcH/VfcT3hC8ty4ig7iks9AK498WQ1mfdmVvcn5Iq3hFSEhh21Bm8lRN8tkEWtrBZdRip5AqxC8zCeHYcDhhqghMANqw1Z4fl3Adii0G1lgpXe0Z1Z7eYTcUD1oqsLqN2Mt4ZNDcwt5MR8RogsVe4Nzdfx7SGnq+fNtXTevNkYGRzEbZVWO+R/jp6Kpmx6F42MZhtNJnH1XeF0mYEK63mVTlVJO6C82yxIgPGeZmZhoreU1uYQmoS4JVsn8qoxq9IIgO9oS4Wzk0MpHYRhpyfJMyqz/OxMfeWDVzXo+CKThJ7vOmSioaSRrxkGL+LvZeXzfjIbIB9Z9697yyjrj086ngNEsh9X94JsmDmmJvgQ1NOBud/jGHdWAzW+Rex/cU8KLKrI/XgWoxtgZlGi/QNFyPbayG0uMTFAVOs0TgK0hL8mJOuJO5tHMJBqJ6U5s7wydBbbLP/4Vo5hh2pRmX1MQHVKhEdmgTm3pbsZeqQbVPvlA4kP73SAGZEumdw8MpMPQ6UZPgV53EpTX5kU9ErBiTLyhB03errWOKObdNhhxQhaIa8s7/Bd4GCICiQ8AxKYcjmbw==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-ro-secret
      namespace: payload01
    type: kubernetes.io/dockerconfigjson

