apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-ro-secret
  namespace: msp
spec:
  encryptedData:
    .dockerconfigjson: AgBgA7nXaiBDixB9ka7VjT4UNLHw0HO6TPkm9a9VQItB6AxmiOlW1BZpTK7KUpKk4saCcMJC9texHCxIDvIrtu3196oCjbKJ03yA8fr3Wotz7IuMVrZC03ucUEZ2tHInJrzWwC1VdKiINDKjw06xFKuGSVmftiaxHn76gHUbzhRBNgks6Y2gSmFkH6F1QvGMcCeGQkeqVuYjkF4X6oLp39JmBjlz0MBfGNZQdFNbY4QoP7bYdOYU1xQsF/u9+aYoHmj83rRbuPi0yskBtfMru9gq/CRbfy7vFrMsznY+UkrnVWoK2fxHod7Ky7TABCq9xg/A+FjfWjkZP8fGp7/2SljTv8or4tgCukJKiM7y+DKI1GKBm/DXRQR+Ez7d5YM9fkshJRrk5FTclkOm7QqpgH+AxZBoDVcrpWMl1HQanKdRsT3y/YQrz8SfIXHJcw2rwr6G/S49bjLIudmtx47NIAeKW0N1jjD8lOsSaOALqEYBFudXa/WssWAGCNkrlaLP+uULG1T0E5xa6Cs/Uaj8qL4Bd1DNk9dLO5GHocd4vP/q88Bolqi+8FutBQFBfSR3O+OJdeiNyht79VX+ZVzGBHxwsQ5wgWm7KSLehd8uRUBAruBi42SD056JYnH5Fjvs65x74zvtAQhyxBtwVlG1ID8td9ygvNngBw1OvrI+kVd381+ZSEleQ3aNkP2BZvh7QunJKrwZhg34z283hXIQVD6ZWRNXgiyOJ6fD/vWXcTcPQFC9q/5QQXa2CNBXmmCEMtV3oOhYJqlUq7TwthX1fel184tDFLsbikaK6p0C6+EVlrp1UsOfJmGMoPv3k36oKphaeR/n6W5F8aNP/p6jZLa4gG76HMZxt49AEHb1MbnVWxOjUjdKamGDRE5mpaYz72BQumM+NUUJN1UF3mTYDCNQT9oIoxRT4a/0iuyQqXh80e56VUYC9xcCh0HcFq49PopFaC13BXkbvlV3QqjW+CAX7+a0EZ9vfYJ8ty2ZXmp27ErU/w==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-ro-secret
      namespace: msp
    type: kubernetes.io/dockerconfigjson

