---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-ro-secret
  namespace: crk8s-system
spec:
  encryptedData:
    .dockerconfigjson: AgCKKvUfLw4de4qJ9eYkQgjCEhaWGBzjCZCZMBX+zKea808pGGn3yE8tuoeeE8rH98DA3PsfugTO83CyPVm35PdfhwAoYX/8zuv2D4CVdw2YtaqTE7ZrMn5hS6x17cAl//VgFd9wHm/R60zoN+IWZk5ZJ+pRfd3w5ZN0tFSj9ZYc5AoBCfLqeaM6lpHV0nkDNaAd1f+dZ4MwS45mONBA3n5L/r2GsPSNjkUoJ1OsioZK2BNmMMCCzmOy8skhRFr7N+fw8hr0LWk46jb9boOaAhTh7GUSax9/a71tsicrq1WqJg0ut7+4cZiXEpQi8tWZE844e1u6TinJrEkqdqRdYn3xh6yoxUmypPC8XaXao71lGDads6dkdfzISJn+fTOHi1VFuvgLNbxMrCbGsZlLZPIjfxuYT8xIUDvFBCdxT27FGTZdvanVTIZ/PRPhm9yFMGyabMeH+qNrm66CexXm8smRkFZNnKTc27Se2OyOhLWeITSANMp+zx6dlcNZ+olQy4ntSucOsdySctpIB8Bi1yI1N2M43TJ0oVgW9ef8dMhe6NZduXFEnS8SC21UGJE1wDPoWPtiGzDhH2OzMave4vmAzdnaICUAlKXRJbzLseVabpwZM9vv5a6bswjlmhuYgiAeBPg2l7LOrWmNzZvIg1G38AJ/qg44bzY0Spaep1fEgD7hDwrihio0Nll1MbGlym3za1N6ltOxAYiLhjx7llF/4GOA3grG9+EO3TJh2poaL+RIAeKh4tXx4FeED8LzxsSKY+j2Y3M+Orl8Xz3wzrRD4qbkjkkTZvID/7FP6fbhyqNnTyjiT+h/dI6v0Qu4XGC9q0PPycdrF9WgPWVWpfy0Av+pz5i1nhjKaFX9OfIW8nizZYr4UuPvRAQtCFAStep9bHkCJMm80Rn6muaoRs5w
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-ro-secret
      namespace: crk8s-system
    type: kubernetes.io/dockerconfigjson
