apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: shelly-shellymock


namespace: mspbase01-hardware
# Example configuration for the webserver
# at https://github.com/monopole/hello
# commonLabels:
#   app: nginx

# resources:
# # Example configuration for the webserver
# # at https://github.com/monopole/hello
#   nameSuffix: -usc206
#   commonLabels:
#     app: shelly-shellypro3
#     variant: test

resources:
- ../../base
- ShellyPro3-configmap.yaml

nameSuffix: -shel209
# patchesStrategicMerge:
#   - deployment.yaml

patches:
  # change configmap names to account for s/n suffix
  - target:
      kind: Deployment
      name: shelly-shellymock
    patch: |-
      - op: replace 
        path: /spec/template/spec/volumes/0/configMap/name
        value: shelly-shellymock-config-shel209
      - op: replace 
        path: /spec/template/spec/volumes/1/configMap/name
        value: controller-definition-shel209
