# datasets/dataset-generation/dataset-generator/base/dataset-generator-service.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dataset-generator
  # namespace: envds
spec:
  template:
    metadata:
      annotations:
        # Keeping at 1 for dev/debugging so you can read logs immediately. 
        # Change to "0" when you want true scale-to-zero in production.
        autoscaling.knative.dev/min-scale: "1" 
    spec:
      imagePullSecrets:
      - name: ghcr-ro-secret
      containers:
        - image: ghcr.io/noaa-pmel/msp/dataset-generator:0.20.0 # Update with your actual registry path
          envFrom:
            - configMapRef:
                name: dataset-generator-config
          volumeMounts:
            - name: shared-calculations
              mountPath: /app/calculations/
            - name: definitions-volume
              mountPath: /app/config/definitions/
      volumes:
        - name: shared-calculations
          configMap:
            name: dataset-generator-calculations
            optional: true
        - name: definitions-volume
          configMap:
            name: dataset-definitions
            # optional: true