nameReference:
- kind: ConfigMap
  version: v1
  fieldSpecs:
  # Tells Kustomize to update ConfigMaps inside Knative Volume Mounts
  - path: spec/template/spec/volumes/configMap/name
    kind: Service
  # Tells Kustomize to update ConfigMaps inside Knative envFrom blocks
  - path: spec/template/spec/containers/envFrom/configMapRef/name
    kind: Service