# datasets/dataset-generation/dataset-generator/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dataset-generator-service.yaml
  - dataset-generator-triggers.yaml
  - ../../../../shared-libs/calculations/base

configurations:
  - knative-kustomizeconfig.yaml

configMapGenerator:
- name: dataset-generator-calculations
  files:
    - ../../../../shared-libs/calculations/base/default.py