apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-ro-secret
  namespace: pmel-pco2
spec:
  encryptedData:
    .dockerconfigjson: AgBBtDftFQSNKrF0fZebSly9NbbxoSdfCGDQbDD+V0H0fpV6/ILZ+jhUUK6Sii8l+AXFS3JhxGtkEtTtR+wV/wllBRmU7388EV5fffeloqaZ8WeRzMaURIblQHeb25iRZ6qQk+iPRZAEeDezeINueQtF4CL7VkYmV37yP03kyAPsIMMwUKwC1Ie5unBGvPR2avH8Z7SS2N7fFlL3/wlNl0LsbMXHPVd0rvMx8V588eDQ9MZGkDY3mn7x0DKJEpzTHk6VSJzhai2gFJJflSpBc9yd9X0v4ZpV4u3u9YDaJhFplWP/7mC0qiMg/l++opy0uvXkNRS7isM5u7h/7jeda5VVuF22fX9TACMyCnORgm6T4SQEc+8OV0L3iiwCthnYaQgVl3JTAzlkiZCbcLSwDtPzzvI4gsuOK1NDwxiNq9NDNZD7tHej3xT3eZtXp9cmlETxVsJuKjjOsLP9lKIWQxfdQUiToUuEkZ7fhgt7okafVvxzRnDbHp2dgMNRTqG1HsD5R1zJhbKoKtDbKin7XmE0AAj3Exr3h1FLrx1DPAeM91iLaqpqCu4Ynd4pkamw+hBNCFsmHfnBWhyJVnrVHqzByb9pe+KSSGVlXY5vYOkfPhsX0CDVkfmwO+yMaj9hc3B1uMKyBQRTiD3wABOBqHnfxbbs3PBfzMZCah4IpUKLfeW3iK1vae4NR3b9P/WuUtUEQXtuFVYysPAC6J5Dt1rULzbcZYkIWH9/ePbnpz0PhO//vQ+GagoB5VIz8RJgc/U0JAg7dOwniejo9vxjHIp1osU3TyPrIP+P6zROqr/QNWYWZZQwRg65eiShG5kBZUjigNDCNj0kOMyLLsLqGwcQloUlyT3z1wdyoQ4afHepFF/yZ005+pEvgieDVCQDlr+mK+4SxmcqSQY3wxDKKYjq
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-ro-secret
      namespace: pmel-pco2
    type: kubernetes.io/dockerconfigjson

