apiVersion: v1
kind: PersistentVolume
metadata:
  name: chunked-filemanager-efs-pv
  labels:
    type: efs-sc
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc # Matches the PVC configuration
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07e5bdd3919c7185c # REPLACE WITH YOUR MANUAL AWS EFS ID