apiVersion: v1
kind: ConfigMap
metadata:
  name: tsi-aps3321-config
  # namespace: msp
  labels:
    app: tsi-aps3321
    # app-group: envds-sensor-payload03
    app-group: envds-sensor-crk8s
data:
  namespace_prefix: payload03 
  envds_env_id: payload03
  # namespace_prefix: mspbase01 
  # envds_env_id: mspbase01
  sensor.conf: |
    serial_number: "273"
    daq_id: payload03
    # daq_id: mspbase01
    interfaces:
      # default: serial
      default:
        interface_env_id: payload03-hardware # if omitted, defaults to envds_id of sensor
        # interface_env_id: mspbase01-hardware
        interface_id: USconverters::USCDR301::usc13
        path: port-1
      #   connection-properties:
      #     baudrate: 115200
      #     bytesize: 8
      #     parity: N
      #     stopbit: 1
      #   # read-properties:
      #     read_method: "readline" # default
      #     # terminator: "\r"
      #     # binary: true
      #     # num-bytes: 1
      #     # decode-errors: strict
      # # power: # example of second interface (e.g., CDP enable signal)
      # #   interface_id: system::mock::localhost
      # #   path: port-01
      
    # settings: # used to override defaults
    #   pump_power: 1
    #   q_target: 300