apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: sampling-conditions
namespace: payload01-system

resources:
- ../../base
- sampling-conditions-configmap.yaml

configMapGenerator:
  - name: sampling-conditions-conditions
    files:
      - ../shared_configs/templates/conditions/payload01_power_states.json

nameSuffix: "-payload01"

patches:
  - target:
      kind: Service
      name: sampling-conditions
    patch: |-
      - op: replace 
        path: /spec/template/spec/volumes/0/configMap/name
        value: sampling-conditions-conditions-payload01
  - target:
      kind: Trigger
    patch: |-
      - op: replace 
        path: /spec/subscriber/ref/name
        value: sampling-conditions-payload01

configurations:
  - config.yaml


# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# metadata:
#   name: sampling-conditions

# # set namespace
# namespace: payload01-system

# # Example configuration for the webserver
# # at https://github.com/monopole/hello
# # commonLabels:
# #   app: nginx

# # resources:
# # # Example configuration for the webserver
# # # at https://github.com/monopole/hello
# #   nameSuffix: -usc206
# #   commonLabels:
# #     app: usconverters-uscdr301
# #     variant: test

# resources:
# - ../../base
# - sampling-conditions-configmap.yaml
# # - platform_defs_configmap.yaml
# # - platform_varmaps_configmap.yaml
# # - ghcr-secret-msp-system-sealed.yaml
# # uncomment this if using knative for data updates
# # - sampling-conditions-triggers.yaml

# configMapGenerator:
#   - name: sampling-conditions-conditions
#     files:
#       - sampling_conditions.json

# nameSuffix: "-payload01"

# patches:
#   # change configmap names to account for s/n suffix
#   - target:
#       # version: serving.knative.dev/v1
#       kind: Service
#       name: sampling-conditions
#     patch: |-
#       # - op: replace 
#       #   path: /spec/template/spec/volumes/0/configMap/name
#       #   value: sampling-conditions-payload01
#       - op: replace 
#         path: /spec/template/spec/volumes/0/configMap/name
#         value: sampling-conditions-conditions-payload01
#   - target:
#       kind: Trigger
#       # name: default
#     patch: |-
#       - op: replace 
#         path: /spec/subscriber/ref/name
#         value: sampling-conditions-payload01


# configurations:
#   - config.yaml

# # patches:
# #   - patch: |-
# #       apiVersion: apps/v1
# #       kind: Deployment
# #       metadata:
# #         name: REPLACED_DURING_PATCH
# #       spec:
# #         template:
# #           spec:
# #             containers:
# #               - name: webhook
# #                 env:
# #                   - name: WEBHOOK_DISABLE_NAMESPACE_OWNERSHIP
# #                     value: "true"
# #     target:
# #       group: apps
# #       kind: Deployment
# #       name: ".*webhook.*"