apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registrar-raz1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: msp
  source:
    repoURL: https://github.com/NOAA-PMEL/msp-gitops.git
    targetRevision: HEAD
    path: kustomize/apps/registrar/overlays/raz1
    # kustomize:
    #   patches:
    #     - patch: |-
    #         - op: replace
    #           path: /spec/subscriber/ref/namespace
    #           value: raz1
    #       target:
    #         kind: Trigger
  destination:
    server: https://kubernetes.default.svc
    # namespace: payload01
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  # ignoreDifferences:
  #   - group: serving.knative.dev
  #     kind: Service
  #     jsonPointers:
  #       - /metadata/annotations
  #       - /metadata/labels
  #       - /spec/template/metadata/annotations
  #       - /spec/template/metadata/labels
  #       - /spec/traffic
  #       - /spec/template/spec/containerConcurrency
  #       - /spec/template/spec/timeoutSeconds
  #       - /spec/template/spec/enableServiceLinks
  #       - /spec/template/spec/containers/0/name
  #       - /spec/template/spec/containers/0/readinessProbe