apiVersion: v1
kind: ConfigMap
metadata:
  name: sampling-system
  # namespace: msp-system
data:
  daq_id: mspbase01

  # --- ADDED FOR ROLE-BASED COMPUTE DELEGATION ---
  node_id: "mspbase01"
  # node_roles: "data-server"
  node_roles: "field-server"
  # -----------------------------------------------

  port: "8080"
  knative_broker: "http://broker-ingress.knative-eventing.svc.cluster.local/mspbase01-system/default"

  mqtt_broker: "mqtt.mspbase01-system"
  mqtt_topic_subscriptions: >
    envds/+/+/+/data/update,   
    envds/+/+/+/controller/data/update,
    envds/+/+/+/settings/update,
    envds/+/controller/settings/update,
    envds/+/variableset/+/data/update   
  
  mqtt_port: "1883"

  log_level: info
  tick_delay_direct: "1.0"
  tick_delay_calc: "2.0"

