apiVersion: v1
kind: ConfigMap
metadata:
  name: sampling-system
  # namespace: msp-system
data:
  daq_id: mspbase01

  # --- ADDED FOR ROLE-BASED COMPUTE DELEGATION ---
  node_id: "mspbase01"
  node_roles: "data-server"
  # -----------------------------------------------

  port: "8080"
  knative_broker: "http://broker-ingress.knative-eventing.svc.cluster.local/mspbase01-system/default"

  mqtt_broker: "mqtt.mspbase01-system"
  mqtt_topic_subscriptions: >
    envds/+/+/+/data/update,   
    envds/+/+/+/controller/data/update   
  
  mqtt_port: "1883"
