apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: system-modes-requirement-status-update
spec:
  broker: default
  filter:
    attributes:
      # Receives SamplingMode and SystemMode status updates for requirement evaluation
      type: envds.status.update 
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: system-modes
    uri: /requirement/status/update/
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: system-modes-remote-transition-request
spec:
  broker: default
  filter:
    attributes:
      # Receives forced transition commands from other nodes
      type: envds.system-modes.transition.request
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: system-modes
    uri: /system/transition/event/