apiVersion: v1
kind: ConfigMap
metadata:
  name: shelly-shellypro2-config
  # namespace: msp
  labels:
    app: shelly-shellypro2
data:
  namespace_prefix: raz1
  envds_env_id: raz1
  controller.conf: |
    uid: shel227
    host: 10.55.169.227
    client_host: mqtt.raz1-system
    client_port: 1883
    controller_id_prefix: shellypro2

    # override definition values
    attributes:
      serial_number: shel227
    # variables:
    #   channel_2_power:
    #     default_value: "0"
