apiVersion: v1
kind: ConfigMap
metadata:
  name: sampling-conditions
  # namespace: msp-system
data:
  daq_id: mspbase01

  ENVOPS_DEPLOYMENT_REF: "deploy.pmel.msp_enclosure_01_at_marina"

  port: "8080"
  knative_broker: "http://broker-ingress.knative-eventing.svc.cluster.local/mspbase01-system/default"

  mqtt_broker: "mqtt.mspbase01-system"
  mqtt_topic_subscriptions: >
    envds/+/variableset/+/data/update

  mqtt_port: "1883"

# off
    # envds/+/+/+/data/update,   
    # envds/+/+/+/controller/data/update   
