apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: erddap-secret
  namespace: pmel-dev-system
spec:
  encryptedData:
    insert-password: AgBl96beIRa0sCRGa90GuXk0/dDay8JRUjTZ5JRpqRMHkDgXkqPv/vYpTTkgMEsY1POKS0Z8kXJO2+VLxO5uTBTampA2asLxnKbefn4LU3y8dkd5DNOaKEu4P/sFSpAzdMbGCvJ0zJji8hwi8FNw+KnXeCfkidOgipmBcDCUJ9Se2Oviv9tzuW71R3X21IFulOkDGoDuJrRUOtqh83Jthn/Ovhdyt+4WgYlbqSr0GcWOtvtVKtAHxlsBI/IST5WeCDULYXz8K2iojSBDZ+iW0uraQmAhbgSXZtsLvSxe4aZhhhBWJXZKiFr624ihptEm+YQnYB8k6HCZydq22RWjAGGtnxDEPEzJfspUg1KsKL6nCwOjaFJWt/PM+qNLTVPdhvNfCUKVuKePHyb6OB+EjuIW4nbsa77x8TxoDQ1YdasXBTobJuDZzhC3enM+bMraq1tXA8JcK+DGidq48MNrN0wEo3mUIn0CQW353US3errztVkIl8/qyMBZAg2mIkyuFqCVWQbZmzbDgNBANugPSYDMB1CjrCWUBc3MdlA5kW0FYgc6OCN/ST0HGKbA+yy6OubBTlmQZLOqPMa/M1HtZ1XJApOAEBdzDIks+q433X/c59KBiRI4Cn1HjzW0q5mldXtrKCgegoLbln+V9ZyGU5TTLfJV0rLspAwvZ58T96iKnqDqqL3VewlC540dzT1mS8aGWDnrvMSZ8as9WUVud0/E
  template:
    metadata:
      creationTimestamp: null
      name: erddap-secret
      namespace: pmel-dev-system

