apiVersion: v1
kind: ConfigMap
metadata:
  name: erddap
data:
  ERDDAP_SIDECAR_DAQ_ID: "pmel-dev"
  ERDDAP_SIDECAR_LOG_LEVEL: "debug"
  ERDDAP_SIDECAR_MQTT_BROKER: "mqtt.pmel-dev-system"
  ERDDAP_SIDECAR_MQTT_PORT: "1883"
  ERDDAP_SIDECAR_MQTT_SUBSCRIPTIONS: "envds/+/+/+/data/#,envds/+/+/+/status/#,envds/+/operations/log"
  ERDDAP_SIDECAR_ERDDAP_INTERNAL_URL: "http://127.0.0.1:8080/erddap"
  ERDDAP_BASE_URL: "http://k8s.pmel-dev.oarcloud.noaa.gov/envds/data"
  ERDDAP_BASE_HTTPS_URL: "http://k8s.pmel-dev.oarcloud.noaa.gov/envds/data"