apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-rwx
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3" # Recommended for high availability
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4" # Or "xfs"
  migratable: "false"
  nfsOptions: "vers=4.1,noresvport,softerr,timeo=600,retrans=5" # Required NFS mount options
