apiVersion: v1
kind: ConfigMap
metadata:
  name: system-modes
  # namespace: msp-system
data:
  daq_id: pmel-dev

  deployment_ref: "deploy.pmel.msp_enclosure_01_at_marina"
  
  port: "8080"
  # knative_broker: "http://broker-ingress.knative-eventing.svc.cluster.local/pmel-dev-system/default"
  knative_broker: "http://kafka-broker-ingress.knative-eventing.svc.cluster.local/pmel-dev-system/default"
  

  system_init_control: "auto"
  system_init_mode: "normal"
  is_primary_controller: "false"

  mqtt_broker: "mqtt.pmel-dev-system"
  mqtt_topic_subscriptions: >
    envds/+/+/+/data/#,
    envds/+/system-modes/#,
    envds/+/sampling-modes/#

  mqtt_port: "1883"
