apiVersion: apps/v1
kind: Deployment
metadata:
  name: msp-manage
  namespace: msp
  labels:
    app: msp-manage
spec:
  selector:
    matchLabels:
      app: msp-manage
  template:
    metadata:
      labels:
        app: msp-manage
    spec:
      imagePullSecrets:
      - name: ghcr-ro-secret
      containers:
      - name: msp-manage
        # image: envds-registry:5000/core/envds-manage:0.1.0
        image: ghcr.io/noaa-pmel/msp/msp-manage:0.1.0
        imagePullPolicy: "Always"
        env:
          - name: ENVDS_ID
            value: mspbase01
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 9080
          protocol: TCP