apiVersion: v1
kind: ConfigMap
metadata:
  name: kld-kld20s-config
  labels:
    app: kld-kld20s
data:
  namespace_prefix: payload02
  envds_env_id: payload02
  operational.conf: |
    serial_number: "cyclone"
    daq_id: payload02
    interfaces:
      valve_control:
        interface_env_id: payload02 
        interface_id: LabJack::Tx::ljtx31 
        path: dac-0 

    settings:
      valve_state: 0 # initialize valve off (e.g., total aerosol line)