apiVersion: v1
kind: ConfigMap
metadata:
  name: sampling-modes
  # namespace: msp-system
data:
  daq_id: revpi1

  # --- 1. GITOPS IDENTITY INJECTION ---
  SAMPLING_NAMESPACE: "pmel.noaa.gov"
  ENVOPS_DEPLOYMENT_REF: "deploy.pmel.payload_alvan_01_in_acg_alvan"
  
  # --- 2. GRANULAR REVISION TIMES (Scoped to PMEL) ---
  DISABLE_CPC_REV_TIME: "2026-06-23T21:00:00Z"
  PMEL_STARTUP_MODE_REV_TIME: "2026-06-23T21:00:00Z"
  PMEL_NOMINAL_MODE_REV_TIME: "2026-06-23T21:00:00Z"

  # --- 3. SENSOR-AGNOSTIC WIRING ---
  # Wires the pmel_disable_cpc_power action to the specific power controller
  CPC_POWER_VARMAP: "payload_alvan_01" 
  CPC_POWER_VARSET: "power"
  CPC_POWER_VAR: "power_cpc"
  # ---------------------------------
  
  port: "8080"
  knative_broker: "http://broker-ingress.knative-eventing.svc.cluster.local/revpi1-system/default"

  is_primary_controller: "true" # ADD THIS LINE

  mqtt_broker: "mqtt.revpi1-system"
  mqtt_topic_subscriptions: >
    envds/+/+/+/data/#,
    envds/+/sampling-states/#,
    envds/revpi1/sampling-modes/#


  mqtt_port: "1883"
