apiVersion: v1
kind: ConfigMap
metadata:
  name: sampling-modes
  # namespace: msp-system
data:
  daq_id: revpi1

  ENVOPS_DEPLOYMENT_REF: "deploy.pmel.payload_alvan_01_in_acg_alvan"
  
  port: "8080"
  knative_broker: "http://broker-ingress.knative-eventing.svc.cluster.local/revpi1-system/default"

  is_primary_controller: "true" # ADD THIS LINE

  mqtt_broker: "mqtt.revpi1-system"
  mqtt_topic_subscriptions: >
    envds/+/+/+/data/#,
    envds/+/sampling-states/#,
    envds/revpi1/sampling-modes/#


  mqtt_port: "1883"
