apiVersion: v1
kind: ConfigMap
metadata:
  name: sampling-system
  # namespace: msp-system
data:
  daq_id: pmel-dev

  # --- ADDED FOR ROLE-BASED COMPUTE DELEGATION ---
  node_id: "pmel-dev"
  node_roles: "data-server"
  # -----------------------------------------------

  port: "8080"
  knative_broker: "http://broker-ingress.knative-eventing.svc.cluster.local/pmel-dev-system/default"

  mqtt_broker: "mqtt.pmel-dev-system"
  mqtt_topic_subscriptions: >
    envds/+/+/+/data/update,   
    envds/+/+/+/controller/data/update   
  
  mqtt_port: "1883"
