apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-ro-secret
  namespace: revpi2-system
spec:
  encryptedData:
    .dockerconfigjson: AgCO/I7Dfv8zMvde8keTU+IwsjfLiXEFICelKeRlCNmt/e17V3wux/Hwr9m+gucay7mbySNjdnnmUIUAo5BgI4a+oXu/aDFWg99SiNTEktZCGDehWiWx0ka4xrDY7xemtHrW6wuwaqw0AU3kN7l1kmaGQI9CrlqF2EuQse9K9Wosny5qRzyTFflUbXZO7FzqYPvgISNsNFitudzFZ4+RVLe/b3TfPhXE3Z5R0PIiZDEPcDOFR/58O02qH/9SFf4EsI9EtUtiVDbW4LhcGtWVDCVVhJ4Wu5dl/8LCxqRji5uXya8GXV5w7q4aspxZYC2D/2sjpR/65VVRSjmC7fgH2y9S8rLQpqFF9j+93ZXKXTSJdB0TPYjj+hoYoUef0VY1hO8H11qJXv7UDNnorn4sxUWtyq7SIbCJAupzJ2OvLMmw0Gy/ZPPlCceAFUCBz0IB5QHIpx6eRHh/4kv2r06+IfKSCQelaKmEsjRjVBaM4l08M2dtBPA0z4ofDGyT8tnmzXMoc0Cp75tnmnMfQky/Vej4Ug5k/T4GodtY4tQGch7FnS+rUkGtoxenAd/SdadgZ+r979//p7OwofSHD4qqNp4DFOK9yPXHuBIAA+IBRPqsdaliKnmt6UQa97z1yN/oafZ39CEPSSa34pLwX8OHjyt0XzXsCRjgCSo4CyXUQeegxAgiPbpOpBAZR0TuI8alGQEayxqvfTk7RBXYz5yJO+xGS91wbQZhy9bUxiZjW7uvres3wxr1yU/vtjnDyH3SmDmEvb+UniCcHl/ddZ81743vddYKm9xixJINTVlurJp5GWf3L4c3l6yFpBUnOSx4rowXlMmzetggwxWehhvFNpx0eSM8JeJfzMjpoZm7UjuHmRytRTg6Iu/R/QR2sctYvpJu48zBag0E7KI0KXDKngy+
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-ro-secret
      namespace: revpi2-system
    type: kubernetes.io/dockerconfigjson


