apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: filemanager-device-data-update
  # namespace: msp-events
spec:
  broker: default
  filter:
    attributes:
      type: envds.data.update
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: filemanager
      # namespace: msp-system
    uri: /data/save/
