apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pmel-dev-system

resources:
  - ../../base

# Generate the config map for the envFrom block
configMapGenerator:
  - name: qc-operations-config
    envs:
      - configmap.env