apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kn-mqtt-adapter

# Example configuration for the webserver
# at https://github.com/monopole/hello
# commonLabels:
#   app: nginx

resources:
- kn-mqtt-deployment.yaml
- kn-mqtt-service.yaml
# - kn-mqtt-ingress.yaml