---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datastore-db-password
  namespace: crk8s-system
spec:
  encryptedData:
    db_password: AgA1V8BB7XV95VP0U7IRDA4UdVaEXmQAGAwwPGv84r0jySAPxt4rStmk85ygNCNuJEibxNRzDKEQ/cBgHGKHiTjX+K5pF6jh3qdvvSaKMIwi0EHHi9KE99u7ajy5CshxRvuMyniYdgMCdlbPR9UkS2VnpRDbE0pjIP2SI/wLiurDFk9AsEXnTKraZmjrJdy/xengGmV0PHQSqfuQ/f0UQ+np+pYawfvILW+5A/IYure98QVQ0EuP6Cbc8deDjhTEtzEnbD1rSJtB6l67xHAE3bDvbgkdDjHWzF8lyPdBrRvWZ4U7EpH+WLBVqCCgN1ONlM9D8yE0UTmujjOW/DmM5x2KcjuU1z5Yu4A7uacGo0O3yQi/1RrxY+wMbswsxS3d5B/xlGO7jS4DPv6XSfH0QaLIVCKAN2nDmKkjxyjmhzLl5NhzyvgEnjUDkl1Hc2RJWEoY9UfVpMV1dX848dO6E+uB4GJOhsF3YikLUXyQA+UKIeHqz1kBMJbX/PcqYdIrwxqssPj7+qyA94/mvS5fwhxl/fbaIXEtNyTQOE2GocCctGk0eYqV9VCfUJP9hQBd2Q7cuzUUUYItuvPRMqBF6MbE0lcascc7eHeyOxBYLMsxRiTBQ2+vY0Idgs4LXNkiHe8+g6/ylQO5gPezt0uY3VRnC0U105ea18U5+IzVee8UmqQZ2qMs6KVYMeugTR1jsOxw+hi+Gg==
  template:
    metadata:
      creationTimestamp: null
      name: datastore-db-password
      namespace: crk8s-system
