# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# metadata:
#   name: telemetry-proxy

# namespace: raz1-system

# resources:
# - ../../base
# - telemetry-proxy-configmap.yaml
# - telemetry-proxy-sealedsecret.yaml  # Contains your ChaCha20 Key

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: telemetry-proxy

namespace: raz1-system

resources:
- ../../base
- telemetry-proxy-sealedsecret.yaml 

# Generate the ConfigMap dynamically to trigger pod restarts on change
configMapGenerator:
- name: telemetry-proxy
  literals:
    - mqtt_broker=mqtt.raz1-system
    - mqtt_port=1883
    - log_level=INFO
    - transmission_rate_hz=5.0
    - bridge_topic_out=envds/transport/compressed/edge-to-cloud
    - bridge_topic_in=envds/transport/compressed/cloud-to-edge
    
    # Use ">-" to fold these multiple lines into a single, clean comma-separated string
    - >-
      local_intercept_topics=envds/+/sensor/+/data/update,
      envds/+/controller/+/controller/data/update,
      main/envds/+/registry/sync-bcast,
      main/envds/+/registry/sync-update,
      main/envds/+/registry/sync-request,
      envds/+/device-instance/registry/update,
      envds/+/controller-instance/registry/update,
      envds/+/controller/settings/update,
      envds/+/sensor/+/settings/update,
      envds/+/system-modes/status/update