apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telemetry-proxy-secret
  namespace: raz1-system
spec:
  encryptedData:
    encryption_key: AgA3RSMX+YjCAjhKme/IFQGXpbl3SOo+G0HiTC3ZBMbYajPrs4Y6GJ7nVVv4VIqGfm4Qy6gUtHUkmHJfEKwVBVDQ4cE9623ZK98KNXeAO6TNe+um6kz0LgndDn4X30WZBUjGV6kWx1iL7S2h3lGTXZHov4jgLzYAmTKR5nf/9g0B2+ZQ1lB3lnUxC74t7ZV8sUzZCEJOhp0J2Bd+9HoAcFD7qFObcE8dFGtWf0swyRnC0GuoUnq1+kKfWyU1/sUYfe02XjpTo7hferxGF1qpAN0uJ5+5RY7e6UNM2zUE8mSUhFbADfDkVDpeOTCcbmTlu1KkByCiC9tHrCCLJ55TT7Qt/eLPcD2qcFIZSr/zjy+0VDqcvIdIQypz/OgHWk0Jd8taHhc+ZgKv6l2DHCeMH9zVJleziabzuScIkt0rPqyr9L3074VxxZLdOL5SaSJqw2hP0BXUVrc6XeTCHlUInlIgymJSPubrsP6AnyA3qe3ryV4wPA64pcddBvnsMtc5S4aDWol1+RQCtNGq7sb9/3fDrIq1DCbg2lDqsw4pqAh1Kcn1vlpfp9RYYXksTetCA10cfsLDKKiRrgbBW4eRQRYnl4oI+yRpC5/CU+4IPYT3uNonxyNUG5PMGo2Iyefka1r4xsL4HpTGCo3XMJYiCbHjVL/b/4uLJZsipSFdDaG/GoYatzHmpp1D0OlhcegQNnbjnj3wxfLOzVOGHrl13T6/x7qAKDJKkGvA0NBrgoVKFg==
  template:
    metadata:
      creationTimestamp: null
      name: telemetry-proxy-secret
      namespace: raz1-system

