apiVersion: v1
kind: ConfigMap
metadata:
  name: telemetry-proxy
data:
  mqtt_broker: "mqtt.raz1-system"
  mqtt_port: "1883"
  log_level: "INFO"  # Shows your compression % reduction!
  
  # Edge: Capture these local topics to compress
  local_intercept_topics: >
    envds/+/sensor/+/data/update,
    envds/+/controller/+/controller/data/update,
    main/envds/+/registry/sync-bcast,
    main/envds/+/registry/sync-update,
    main/envds/+/registry/sync-request,
    envds/+/device-instance/registry/update,
    envds/+/controller-instance/registry/update,
    envds/+/controller/settings/update,
    envds/+/sensor/+/settings/update,
    envds/+/system-modes/status/update
  
  # Edge: Send compressed payloads OUT to this topic
  bridge_topic_out: "envds/transport/compressed/edge-to-cloud"
  
  # Edge: Listen for compressed payloads coming IN from the cloud
  bridge_topic_in: "envds/transport/compressed/cloud-to-edge"