apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filemanager-data-pvc
  labels:
    app: filemanager
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-retain # Points to your custom retain class
  resources:
    requests:
      storage: 50Gi