apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: sensirion-sdp810

# Example configuration for the webserver
# at https://github.com/monopole/hello
# commonLabels:
#   app: nginx

resources:
- sdp810-deployment.yaml
- sdp810-service.yaml