apiVersion: v1
kind: ConfigMap
metadata:
  name: aerosoldynamics-magic250-config
  # namespace: msp
  labels:
    app: aerosoldynamics-magic250
    # app-group: envds-sensor-payload01
    # app-group: envds-sensor-revpi01
    app-group: envds-sensor-crk8s
data:
  # namespace_prefix: payload01
  # envds_env_id: payload01
  # namespace_prefix: revpi01
  # envds_env_id: revpi01
  namespace_prefix: crk8s
  envds_env_id: crk8s
  sensor.conf: |
    serial_number: "mock3"
    # daq_id: payload01
    # daq_id: revpi01
    daq_id: crk8s
    interfaces:
      # default: serial
      default:
        interface_env_id: payload01-hardware # if omitted, defaults to envds_id of sensor
        # interface_id: USconverters::USCDR301::usc13
        interface_id: Lantronix::XPort::magic250-154
        path: port-1
      #   connection-properties:
      #     baudrate: 115200
      #     bytesize: 8
      #     parity: N
      #     stopbit: 1
      #   # read-properties:
      #     read_method: "readline" # default
      #     # terminator: "\r"
      #     # binary: true
      #     # num-bytes: 1
      #     # decode-errors: strict
      # # power: # example of second interface (e.g., CDP enable signal)
      # #   interface_id: system::mock::localhost
      # #   path: port-01
      
    # settings: # used to override defaults
    #   pump_power: 1
    #   q_target: 300
