serial_number: "physics"
daq_id: payload01
modbus_address: 1
interfaces:
  default: # to read PV and write SV via serial-to-TCP gateway
    interface_env_id: payload01 
    interface_id: USconverters::USCDR301::usc26
    path: port-1 # Update to match your target COM port mapping
settings:
  set_value: 25.0