apiVersion: apps/v1
kind: Deployment
metadata:
  name: labjack-tx
  # namespace: msp
  labels:
    app: labjack-tx
spec:
  selector:
    matchLabels:
      app: labjack-tx
  template:
    metadata:
      labels:
        app: labjack-tx
    spec:
      imagePullSecrets:
      - name: ghcr-ro-secret
      containers:
      - name: labjack-tx
        # image: registry-msp:5000/msp/interface/labjack-tx:0.1.0
        image: ghcr.io/noaa-pmel/msp/labjack-tx:0.1.1
        imagePullPolicy: "Always"
        env:
          - name: ENVDS_CORE_NAMESPACE_PREFIX
            valueFrom:
              configMapKeyRef:
                name: labjack-tx-config
                key: namespace_prefix
          - name: ENVDS_ENV_ID
            valueFrom:
              configMapKeyRef:
                name: labjack-tx-config
                key: envds_env_id
            # value: mspbase01
          - name: REDIS_OM_URL
            value: redis://redis.default
          - name: LOG_LEVEL
            value: DEBUG
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 9080
          protocol: TCP
        # - name: https
        #   containerPort: 8883
        #   protocol: TCP
        volumeMounts:
            - name: labjack-tx-config
              mountPath: /app/config/interface.conf
              subPath: interface.conf
            - name: interface-definition
              mountPath: /app/LabJack_Tx_interface_definition.json
              subPath: LabJack_Tx_interface_definition.json
            # - name: mosquitto-certs
            #   mountPath: /certs/ca.crt
            #   subPath: ca.crt
            # - name: mosquitto-certs
            #   mountPath: /certs/server.crt
            #   subPath: server.crt
            # - name: mosquitto-certs
            #   mountPath: /certs/server.key
            #   subPath: server.key
      volumes:
        - name: labjack-tx-config
          configMap:
            name: labjack-tx-config
        - name: interface-definition
          configMap:
            name: interface-definition
