apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: raz1-system

resources:
- ../../base
- sampling-modes-configmap.yaml

configMapGenerator:
  - name: sampling-modes-modes
    files:
      - sampling_modes_modes.json
  - name: sampling-modes-actions
    files:
      - sampling_modes_actions.json

generatorOptions:
  disableNameSuffixHash: true

nameSuffix: "-raz1"

patches:
  # change configmap names in the Volumes list to account for the -raz1 suffix
  - target:
      kind: Service
      name: sampling-modes
    patch: |-
      - op: replace 
        path: /spec/template/spec/volumes/0/configMap/name
        value: sampling-modes-modes-raz1
      - op: replace 
        path: /spec/template/spec/volumes/1/configMap/name
        value: sampling-modes-actions-raz1
  # change the subscriber ref in the Knative Triggers to point to the suffixed service
  - target:
      kind: Trigger
    patch: |-
      - op: replace 
        path: /spec/subscriber/ref/name
        value: sampling-modes-raz1

configurations:
  - config.yaml