apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sampling-conditions
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "1"
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/target-utilization-percentage: "70"
    spec:
      imagePullSecrets:
      - name: ghcr-ro-secret
      containers:
        - image: ghcr.io/noaa-pmel/msp/sampling-conditions:0.4.0
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - configMapRef:
                name: sampling-conditions
          env:
            - name: SAMPLING_CONDITIONS_PORT
              valueFrom:
                configMapKeyRef:
                  name: sampling-conditions
                  key: port
            - name: SAMPLING_CONDITIONS_DAQ_ID
              valueFrom:
                configMapKeyRef:
                  name: sampling-conditions
                  key: daq_id
            - name: SAMPLING_CONDITIONS_MQTT_BROKER
              valueFrom:
                configMapKeyRef:
                  name: sampling-conditions
                  key: mqtt_broker
            - name: SAMPLING_CONDITIONS_MQTT_PORT
              valueFrom:
                configMapKeyRef:
                  name: sampling-conditions
                  key: mqtt_port
            - name: SAMPLING_CONDITIONS_MQTT_TOPIC_SUBSCRIPTIONS
              valueFrom:
                configMapKeyRef:
                  name: sampling-conditions
                  key: mqtt_topic_subscriptions
            - name: SAMPLING_CONDITIONS_KNATIVE_BROKER
              valueFrom:
                configMapKeyRef:
                  name: sampling-conditions
                  key: knative_broker
          
          # ---> UPDATED: Mount the entire directory <---
          volumeMounts:
            - name: sampling-conditions-conditions
              mountPath: /app/config/conditions

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
            timeoutSeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
            timeoutSeconds: 10
            periodSeconds: 10
      volumes:
        - name: sampling-conditions-conditions
          configMap:
            name: sampling-conditions-conditions