apiVersion: v1
kind: Service
metadata:
  name: ist-hyt939p
  # namespace: msp
  labels:
    app: ist-hyt939p
spec:
  selector:
    app: ist-hyt939p
  ports:
  - name: http
    protocol: TCP
    port: 9080
    targetPort: 9080
  # - name: https
  #   port: 8883
  #   targetPort: 8883
  # type: LoadBalancer
  type: ClusterIP