apiVersion: v1
kind: ConfigMap
metadata:
  name: sampling-modes
  # namespace: msp-system
data:
  daq_id: mspbase01
  port: "8080"
  knative_broker: "http://broker-ingress.knative-eventing.svc.cluster.local/mspbase01-system/default"

  is_primary_controller: "false" # ADD THIS LINE

  mqtt_broker: "mqtt.mspbase01-system"
  mqtt_topic_subscriptions: >
    envds/+/+/+/data/#,
    envds/+/sampling-states/#,
    envds/mspbase01/sampling-modes/#


  mqtt_port: "1883"
