apiVersion: v1
kind: ConfigMap
metadata:
  name: sampling-modes
data:
  daq_id: payload02
  DAQ_ID: payload02

  # --- GITOPS IDENTITY INJECTION ---
  SAMPLING_NAMESPACE: "pmel.noaa.gov"
  ENVOPS_DEPLOYMENT_REF: "deploy.pmel.payload_02_in_msp_01"
  ACTIONS_REVISION_TIME: "2026-06-11T19:26:00Z"

  # --- SENSOR-AGNOSTIC WIRING ---
  ACTIONS_MODULE: "payload02_actions"
  POWER_VARMAP: "payload_02"
  
  port: "8080"
  knative_broker: "http://broker-ingress.knative-eventing.svc.cluster.local/payload02-system/default"
  is_primary_controller: "true"

  mqtt_broker: "mqtt.payload02-system"
  mqtt_topic_subscriptions: >
    envds/+/+/+/data/#,
    envds/+/sampling-states/#,
    envds/payload02/sampling-modes/#
  mqtt_port: "1883"

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: sampling-modes
#   # namespace: msp-system
# data:
#   daq_id: payload02

#   ENVOPS_DEPLOYMENT_REF: "deploy.pmel.payload_02_in_msp_01"

#   port: "8080"
#   knative_broker: "http://broker-ingress.knative-eventing.svc.cluster.local/payload02-system/default"

#   is_primary_controller: "true" # ADD THIS LINE

#   mqtt_broker: "mqtt.payload02-system"
#   mqtt_topic_subscriptions: >
#     envds/+/+/+/data/#,
#     envds/+/sampling-states/#,
#     envds/payload02/sampling-modes/#


#   mqtt_port: "1883"
