apiVersion: v1
kind: ConfigMap
metadata:
  name: sampling-modes
  # namespace: msp-system
data:
  daq_id: payload02
  port: "8080"
  knative_broker: "http://broker-ingress.knative-eventing.svc.cluster.local/payload02-system/default"

  is_primary_controller: "true" # ADD THIS LINE

  mqtt_broker: "mqtt.payload02-system"
  mqtt_topic_subscriptions: >
    envds/+/+/+/data/#,
    envds/+/sampling-states/#,
    envds/payload02/sampling-modes/#


  mqtt_port: "1883"
