apiVersion: v1
kind: ConfigMap
metadata:
  name: system-modes
  # namespace: msp-system
data:
  daq_id: revpi1
  port: "8080"
  knative_broker: "http://broker-ingress.knative-eventing.svc.cluster.local/revpi1-system/default"

  system_init_control: "auto"
  system_init_mode: "normal"
  is_primary_controller: "true"

  deployment_ref: "deploy.pmel.payload_alvan_01_in_acg_alvan"
  
  mqtt_broker: "mqtt.revpi1-system"
  mqtt_topic_subscriptions: >
    envds/+/+/+/data/#,
    envds/+/system-modes/#,
    envds/+/sampling-modes/#


  mqtt_port: "1883"
