apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payload02-system
resources:
  - ../../base
configMapGenerator:
  - name: system-modes
    envs:
      - system-modes.env
  - name: system-modes-modes
    files:
      - ../../shared_configs/templates/system_modes/payload_normal_system_mode.json
      - ../../shared_configs/templates/system_modes/payload02_startup_system_mode.json
      - ../../shared_configs/templates/system_modes/payload02_shutdown_system_mode.json
      - ../../shared_configs/templates/system_modes/payload02_standby_system_mode.json
      - ../../shared_configs/templates/system_modes/pmel_maintenance_system_mode.json