apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: msp-crk8s
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: msp
  source:
    path: argocd/local/crk8s/apps
    repoURL: https://github.com/NOAA-PMEL/msp-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true