apiVersion: apps/v1
kind: Deployment
metadata:
  name: aerosoldynamics-spidermagic810
  # namespace: mspbase01-hardware
  labels:
    app: aerosoldynamics-spidermagic810
spec:
  selector:
    matchLabels:
      app: aerosoldynamics-spidermagic810
  template:
    metadata:
      labels:
        app: aerosoldynamics-spidermagic810
    spec:
      imagePullSecrets:
      - name: ghcr-ro-secret
      containers:
      - name: aerosoldynamics-spidermagic810
        image: ghcr.io/noaa-pmel/msp/aerosoldynamics-spidermagic810:0.1.0
        # image: registry-msp:5000/msp/sensor/aerosoldynamics-spidermagic810:0.1.0
        imagePullPolicy: "Always"
        env:
          - name: ENVDS_CORE_NAMESPACE_PREFIX
            valueFrom:
              configMapKeyRef:
                name: aerosoldynamics-spidermagic810-config
                key: namespace_prefix
          - name: ENVDS_ENV_ID
            valueFrom:
              configMapKeyRef:
                name: aerosoldynamics-spidermagic810-config
                key: envds_env_id
          - name: REDIS_OM_URL
            value: redis://redis.default
          - name: LOG_LEVEL
            value: DEBUG
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 9080
          protocol: TCP
        # - name: https
        #   containerPort: 8883
        #   protocol: TCP
        volumeMounts:
            - name: aerosoldynamics-spidermagic810-config
              mountPath: /app/config/sensor.conf
              subPath: sensor.conf
            - name: sensor-definition
              mountPath: /app/AerosolDynamics_SpiderMagic810_sensor_definition.json
              subPath: AerosolDynamics_SpiderMagic810_sensor_definition.json
      volumes:
        - name: aerosoldynamics-spidermagic810-config
          configMap:
            name: aerosoldynamics-spidermagic810-config
        - name: sensor-definition
          configMap:
            name: sensor-definition