apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-config
  # namespace: msp-system
  labels:
    app: mqtt
  # namespace: envds-base
data:
  mosquitto.conf: |
    sys_interval 1
    autosave_interval 1
    autosave_on_changes true
    # logs
    log_dest stdout
    log_type all
    log_timestamp true
    log_timestamp_format %Y-%m-%d_%H:%M:%S
    connection_messages true
    # data
    persistence true
    persistence_location /mosquitto/data
    persistence_file mosquitto.db
    per_listener_settings true

    # Non-TLS
    listener 1883
    protocol mqtt
    allow_anonymous true

    # Bridge
    # connection pmel-dev_aws-iot-core_bridge
    # address 10.55.169.210:8883
    # remote_clientid payload01_mspbase01_bridge
    connection pmel-pco2_aws-iot-core_bridge
    address iot.pmel-dev.oarcloud.noaa.gov:443
    # address ayfar3nvv1l0l.iot.us-east-1.amazonaws.com:8883
    remote_clientid pmel-pco2_aws-iot-core_bridge
    # remote_clientid pmel-dev-server
    # bridge_protocol_version mqttv311
    # bridge_protocol_version mqttv50
    # bridge_insecure false
    # cleansession true
    # try_private false
    # start_type automatic
    # notifications false
    cleansession true
    start_type automatic
    notifications false

    # Certificate-based authentication
    bridge_cafile /certs/rootCA.crt
    bridge_certfile /certs/cert.crt
    bridge_keyfile /certs/private.key
    # tls_version tlsv1.2

    # TLS ALPN
    bridge_alpn x-amzn-mqtt-ca

    topic pmel/pco2/+/file/update in 1 "" ""

  